// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2025_2_VKarmane/internal/app/budget_service/grpc (interfaces: BudgetUseCase)
//
// Generated by this command:
//
//	mockgen -destination=mock_budget_usecase.go -package=mocks github.com/go-park-mail-ru/2025_2_VKarmane/internal/app/budget_service/grpc BudgetUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2025_2_VKarmane/internal/app/budget_service/models"
	proto "github.com/go-park-mail-ru/2025_2_VKarmane/internal/app/budget_service/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockBudgetUseCase is a mock of BudgetUseCase interface.
type MockBudgetUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockBudgetUseCaseMockRecorder
	isgomock struct{}
}

// MockBudgetUseCaseMockRecorder is the mock recorder for MockBudgetUseCase.
type MockBudgetUseCaseMockRecorder struct {
	mock *MockBudgetUseCase
}

// NewMockBudgetUseCase creates a new mock instance.
func NewMockBudgetUseCase(ctrl *gomock.Controller) *MockBudgetUseCase {
	mock := &MockBudgetUseCase{ctrl: ctrl}
	mock.recorder = &MockBudgetUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBudgetUseCase) EXPECT() *MockBudgetUseCaseMockRecorder {
	return m.recorder
}

// CreateBudget mocks base method.
func (m *MockBudgetUseCase) CreateBudget(arg0 context.Context, arg1 models.CreateBudgetRequest, arg2 int) (*proto.Budget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBudget", arg0, arg1, arg2)
	ret0, _ := ret[0].(*proto.Budget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBudget indicates an expected call of CreateBudget.
func (mr *MockBudgetUseCaseMockRecorder) CreateBudget(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBudget", reflect.TypeOf((*MockBudgetUseCase)(nil).CreateBudget), arg0, arg1, arg2)
}

// DeleteBudget mocks base method.
func (m *MockBudgetUseCase) DeleteBudget(ctx context.Context, budgetID, userID int) (*proto.Budget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBudget", ctx, budgetID, userID)
	ret0, _ := ret[0].(*proto.Budget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBudget indicates an expected call of DeleteBudget.
func (mr *MockBudgetUseCaseMockRecorder) DeleteBudget(ctx, budgetID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBudget", reflect.TypeOf((*MockBudgetUseCase)(nil).DeleteBudget), ctx, budgetID, userID)
}

// GetBudget mocks base method.
func (m *MockBudgetUseCase) GetBudget(ctx context.Context, budgetID, userID int) (*proto.Budget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBudget", ctx, budgetID, userID)
	ret0, _ := ret[0].(*proto.Budget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBudget indicates an expected call of GetBudget.
func (mr *MockBudgetUseCaseMockRecorder) GetBudget(ctx, budgetID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBudget", reflect.TypeOf((*MockBudgetUseCase)(nil).GetBudget), ctx, budgetID, userID)
}

// GetBudgets mocks base method.
func (m *MockBudgetUseCase) GetBudgets(arg0 context.Context, arg1 int) (*proto.ListBudgetsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBudgets", arg0, arg1)
	ret0, _ := ret[0].(*proto.ListBudgetsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBudgets indicates an expected call of GetBudgets.
func (mr *MockBudgetUseCaseMockRecorder) GetBudgets(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBudgets", reflect.TypeOf((*MockBudgetUseCase)(nil).GetBudgets), arg0, arg1)
}

// UpdateBudget mocks base method.
func (m *MockBudgetUseCase) UpdateBudget(arg0 context.Context, arg1 models.UpdatedBudgetRequest) (*proto.Budget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBudget", arg0, arg1)
	ret0, _ := ret[0].(*proto.Budget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBudget indicates an expected call of UpdateBudget.
func (mr *MockBudgetUseCaseMockRecorder) UpdateBudget(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBudget", reflect.TypeOf((*MockBudgetUseCase)(nil).UpdateBudget), arg0, arg1)
}
