// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2025_2_VKarmane/internal/budget_service/proto (interfaces: BudgetServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=mock_budget_client.go -package=mocks github.com/go-park-mail-ru/2025_2_VKarmane/internal/budget_service/proto BudgetServiceClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	proto "github.com/go-park-mail-ru/2025_2_VKarmane/internal/budget_service/proto"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockBudgetServiceClient is a mock of BudgetServiceClient interface.
type MockBudgetServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockBudgetServiceClientMockRecorder
	isgomock struct{}
}

// MockBudgetServiceClientMockRecorder is the mock recorder for MockBudgetServiceClient.
type MockBudgetServiceClientMockRecorder struct {
	mock *MockBudgetServiceClient
}

// NewMockBudgetServiceClient creates a new mock instance.
func NewMockBudgetServiceClient(ctrl *gomock.Controller) *MockBudgetServiceClient {
	mock := &MockBudgetServiceClient{ctrl: ctrl}
	mock.recorder = &MockBudgetServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBudgetServiceClient) EXPECT() *MockBudgetServiceClientMockRecorder {
	return m.recorder
}

// CreateBudget mocks base method.
func (m *MockBudgetServiceClient) CreateBudget(ctx context.Context, in *proto.CreateBudgetRequest, opts ...grpc.CallOption) (*proto.Budget, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateBudget", varargs...)
	ret0, _ := ret[0].(*proto.Budget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBudget indicates an expected call of CreateBudget.
func (mr *MockBudgetServiceClientMockRecorder) CreateBudget(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBudget", reflect.TypeOf((*MockBudgetServiceClient)(nil).CreateBudget), varargs...)
}

// DeleteBudget mocks base method.
func (m *MockBudgetServiceClient) DeleteBudget(ctx context.Context, in *proto.BudgetRequest, opts ...grpc.CallOption) (*proto.Budget, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteBudget", varargs...)
	ret0, _ := ret[0].(*proto.Budget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBudget indicates an expected call of DeleteBudget.
func (mr *MockBudgetServiceClientMockRecorder) DeleteBudget(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBudget", reflect.TypeOf((*MockBudgetServiceClient)(nil).DeleteBudget), varargs...)
}

// GetBudget mocks base method.
func (m *MockBudgetServiceClient) GetBudget(ctx context.Context, in *proto.BudgetRequest, opts ...grpc.CallOption) (*proto.Budget, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetBudget", varargs...)
	ret0, _ := ret[0].(*proto.Budget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBudget indicates an expected call of GetBudget.
func (mr *MockBudgetServiceClientMockRecorder) GetBudget(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBudget", reflect.TypeOf((*MockBudgetServiceClient)(nil).GetBudget), varargs...)
}

// GetListBudgets mocks base method.
func (m *MockBudgetServiceClient) GetListBudgets(ctx context.Context, in *proto.UserID, opts ...grpc.CallOption) (*proto.ListBudgetsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetListBudgets", varargs...)
	ret0, _ := ret[0].(*proto.ListBudgetsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListBudgets indicates an expected call of GetListBudgets.
func (mr *MockBudgetServiceClientMockRecorder) GetListBudgets(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListBudgets", reflect.TypeOf((*MockBudgetServiceClient)(nil).GetListBudgets), varargs...)
}

// UpdateBudget mocks base method.
func (m *MockBudgetServiceClient) UpdateBudget(ctx context.Context, in *proto.UpdateBudgetRequest, opts ...grpc.CallOption) (*proto.Budget, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateBudget", varargs...)
	ret0, _ := ret[0].(*proto.Budget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBudget indicates an expected call of UpdateBudget.
func (mr *MockBudgetServiceClientMockRecorder) UpdateBudget(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBudget", reflect.TypeOf((*MockBudgetServiceClient)(nil).UpdateBudget), varargs...)
}
