// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2025_2_VKarmane/internal/app/budget_service/usecase (interfaces: BudgetService)
//
// Generated by this command:
//
//	mockgen -destination=mock_budget_service.go -package=mocks github.com/go-park-mail-ru/2025_2_VKarmane/internal/app/budget_service/usecase BudgetService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2025_2_VKarmane/internal/app/budget_service/models"
	proto "github.com/go-park-mail-ru/2025_2_VKarmane/internal/app/budget_service/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockBudgetService is a mock of BudgetService interface.
type MockBudgetService struct {
	ctrl     *gomock.Controller
	recorder *MockBudgetServiceMockRecorder
	isgomock struct{}
}

// MockBudgetServiceMockRecorder is the mock recorder for MockBudgetService.
type MockBudgetServiceMockRecorder struct {
	mock *MockBudgetService
}

// NewMockBudgetService creates a new mock instance.
func NewMockBudgetService(ctrl *gomock.Controller) *MockBudgetService {
	mock := &MockBudgetService{ctrl: ctrl}
	mock.recorder = &MockBudgetServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBudgetService) EXPECT() *MockBudgetServiceMockRecorder {
	return m.recorder
}

// CreateBudget mocks base method.
func (m *MockBudgetService) CreateBudget(arg0 context.Context, arg1 models.CreateBudgetRequest, arg2 int) (*proto.Budget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBudget", arg0, arg1, arg2)
	ret0, _ := ret[0].(*proto.Budget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBudget indicates an expected call of CreateBudget.
func (mr *MockBudgetServiceMockRecorder) CreateBudget(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBudget", reflect.TypeOf((*MockBudgetService)(nil).CreateBudget), arg0, arg1, arg2)
}

// DeleteBudget mocks base method.
func (m *MockBudgetService) DeleteBudget(ctx context.Context, budgetID, userID int) (*proto.Budget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBudget", ctx, budgetID, userID)
	ret0, _ := ret[0].(*proto.Budget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBudget indicates an expected call of DeleteBudget.
func (mr *MockBudgetServiceMockRecorder) DeleteBudget(ctx, budgetID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBudget", reflect.TypeOf((*MockBudgetService)(nil).DeleteBudget), ctx, budgetID, userID)
}

// GetBudgetByID mocks base method.
func (m *MockBudgetService) GetBudgetByID(ctx context.Context, budgetID, userID int) (*proto.Budget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBudgetByID", ctx, budgetID, userID)
	ret0, _ := ret[0].(*proto.Budget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBudgetByID indicates an expected call of GetBudgetByID.
func (mr *MockBudgetServiceMockRecorder) GetBudgetByID(ctx, budgetID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBudgetByID", reflect.TypeOf((*MockBudgetService)(nil).GetBudgetByID), ctx, budgetID, userID)
}

// GetBudgets mocks base method.
func (m *MockBudgetService) GetBudgets(arg0 context.Context, arg1 int) (*proto.ListBudgetsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBudgets", arg0, arg1)
	ret0, _ := ret[0].(*proto.ListBudgetsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBudgets indicates an expected call of GetBudgets.
func (mr *MockBudgetServiceMockRecorder) GetBudgets(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBudgets", reflect.TypeOf((*MockBudgetService)(nil).GetBudgets), arg0, arg1)
}

// UpdateBudget mocks base method.
func (m *MockBudgetService) UpdateBudget(arg0 context.Context, arg1 models.UpdatedBudgetRequest) (*proto.Budget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBudget", arg0, arg1)
	ret0, _ := ret[0].(*proto.Budget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBudget indicates an expected call of UpdateBudget.
func (mr *MockBudgetServiceMockRecorder) UpdateBudget(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBudget", reflect.TypeOf((*MockBudgetService)(nil).UpdateBudget), arg0, arg1)
}
