// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2025_2_VKarmane/internal/handlers/operation (interfaces: OperationUseCase)
//
// Generated by this command:
//
//	mockgen -destination=mock_operation_usecase.go -package=mocks github.com/go-park-mail-ru/2025_2_VKarmane/internal/handlers/operation OperationUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2025_2_VKarmane/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockOperationUseCase is a mock of OperationUseCase interface.
type MockOperationUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockOperationUseCaseMockRecorder
	isgomock struct{}
}

// MockOperationUseCaseMockRecorder is the mock recorder for MockOperationUseCase.
type MockOperationUseCaseMockRecorder struct {
	mock *MockOperationUseCase
}

// NewMockOperationUseCase creates a new mock instance.
func NewMockOperationUseCase(ctrl *gomock.Controller) *MockOperationUseCase {
	mock := &MockOperationUseCase{ctrl: ctrl}
	mock.recorder = &MockOperationUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOperationUseCase) EXPECT() *MockOperationUseCaseMockRecorder {
	return m.recorder
}

// CreateOperation mocks base method.
func (m *MockOperationUseCase) CreateOperation(ctx context.Context, req models.CreateOperationRequest, accID int) (models.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOperation", ctx, req, accID)
	ret0, _ := ret[0].(models.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOperation indicates an expected call of CreateOperation.
func (mr *MockOperationUseCaseMockRecorder) CreateOperation(ctx, req, accID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOperation", reflect.TypeOf((*MockOperationUseCase)(nil).CreateOperation), ctx, req, accID)
}

// DeleteOperation mocks base method.
func (m *MockOperationUseCase) DeleteOperation(ctx context.Context, accID, opID int) (models.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOperation", ctx, accID, opID)
	ret0, _ := ret[0].(models.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOperation indicates an expected call of DeleteOperation.
func (mr *MockOperationUseCaseMockRecorder) DeleteOperation(ctx, accID, opID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOperation", reflect.TypeOf((*MockOperationUseCase)(nil).DeleteOperation), ctx, accID, opID)
}

// GetAccountOperations mocks base method.
func (m *MockOperationUseCase) GetAccountOperations(ctx context.Context, accID int) ([]models.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountOperations", ctx, accID)
	ret0, _ := ret[0].([]models.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountOperations indicates an expected call of GetAccountOperations.
func (mr *MockOperationUseCaseMockRecorder) GetAccountOperations(ctx, accID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountOperations", reflect.TypeOf((*MockOperationUseCase)(nil).GetAccountOperations), ctx, accID)
}

// GetOperationByID mocks base method.
func (m *MockOperationUseCase) GetOperationByID(ctx context.Context, accID, opID int) (models.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperationByID", ctx, accID, opID)
	ret0, _ := ret[0].(models.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOperationByID indicates an expected call of GetOperationByID.
func (mr *MockOperationUseCaseMockRecorder) GetOperationByID(ctx, accID, opID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperationByID", reflect.TypeOf((*MockOperationUseCase)(nil).GetOperationByID), ctx, accID, opID)
}

// UpdateOperation mocks base method.
func (m *MockOperationUseCase) UpdateOperation(ctx context.Context, req models.UpdateOperationRequest, accID, opID int) (models.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOperation", ctx, req, accID, opID)
	ret0, _ := ret[0].(models.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOperation indicates an expected call of UpdateOperation.
func (mr *MockOperationUseCaseMockRecorder) UpdateOperation(ctx, req, accID, opID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOperation", reflect.TypeOf((*MockOperationUseCase)(nil).UpdateOperation), ctx, req, accID, opID)
}
