// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2025_2_VKarmane/internal/app/finance_service/usecase (interfaces: FinanceService)
//
// Generated by this command:
//
//	mockgen -destination=mock_finance_service.go -package=mocks github.com/go-park-mail-ru/2025_2_VKarmane/internal/app/finance_service/usecase FinanceService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2025_2_VKarmane/internal/app/finance_service/models"
	proto "github.com/go-park-mail-ru/2025_2_VKarmane/internal/app/finance_service/proto"
	gomock "go.uber.org/mock/gomock"
)

// MockFinanceService is a mock of FinanceService interface.
type MockFinanceService struct {
	ctrl     *gomock.Controller
	recorder *MockFinanceServiceMockRecorder
	isgomock struct{}
}

// MockFinanceServiceMockRecorder is the mock recorder for MockFinanceService.
type MockFinanceServiceMockRecorder struct {
	mock *MockFinanceService
}

// NewMockFinanceService creates a new mock instance.
func NewMockFinanceService(ctrl *gomock.Controller) *MockFinanceService {
	mock := &MockFinanceService{ctrl: ctrl}
	mock.recorder = &MockFinanceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFinanceService) EXPECT() *MockFinanceServiceMockRecorder {
	return m.recorder
}

// AddUserToAccount mocks base method.
func (m *MockFinanceService) AddUserToAccount(ctx context.Context, userID, accountID int) (*proto.SharingsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserToAccount", ctx, userID, accountID)
	ret0, _ := ret[0].(*proto.SharingsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddUserToAccount indicates an expected call of AddUserToAccount.
func (mr *MockFinanceServiceMockRecorder) AddUserToAccount(ctx, userID, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserToAccount", reflect.TypeOf((*MockFinanceService)(nil).AddUserToAccount), ctx, userID, accountID)
}

// CreateAccount mocks base method.
func (m *MockFinanceService) CreateAccount(ctx context.Context, req models.CreateAccountRequest) (*proto.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", ctx, req)
	ret0, _ := ret[0].(*proto.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockFinanceServiceMockRecorder) CreateAccount(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockFinanceService)(nil).CreateAccount), ctx, req)
}

// CreateCategory mocks base method.
func (m *MockFinanceService) CreateCategory(ctx context.Context, req models.CreateCategoryRequest) (*proto.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategory", ctx, req)
	ret0, _ := ret[0].(*proto.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCategory indicates an expected call of CreateCategory.
func (mr *MockFinanceServiceMockRecorder) CreateCategory(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockFinanceService)(nil).CreateCategory), ctx, req)
}

// CreateOperation mocks base method.
func (m *MockFinanceService) CreateOperation(ctx context.Context, req models.CreateOperationRequest, accountID int) (*proto.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOperation", ctx, req, accountID)
	ret0, _ := ret[0].(*proto.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOperation indicates an expected call of CreateOperation.
func (mr *MockFinanceServiceMockRecorder) CreateOperation(ctx, req, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOperation", reflect.TypeOf((*MockFinanceService)(nil).CreateOperation), ctx, req, accountID)
}

// DeleteAccount mocks base method.
func (m *MockFinanceService) DeleteAccount(ctx context.Context, userID, accountID int) (*proto.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccount", ctx, userID, accountID)
	ret0, _ := ret[0].(*proto.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAccount indicates an expected call of DeleteAccount.
func (mr *MockFinanceServiceMockRecorder) DeleteAccount(ctx, userID, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccount", reflect.TypeOf((*MockFinanceService)(nil).DeleteAccount), ctx, userID, accountID)
}

// DeleteCategory mocks base method.
func (m *MockFinanceService) DeleteCategory(ctx context.Context, userID, categoryID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategory", ctx, userID, categoryID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCategory indicates an expected call of DeleteCategory.
func (mr *MockFinanceServiceMockRecorder) DeleteCategory(ctx, userID, categoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategory", reflect.TypeOf((*MockFinanceService)(nil).DeleteCategory), ctx, userID, categoryID)
}

// DeleteOperation mocks base method.
func (m *MockFinanceService) DeleteOperation(ctx context.Context, accID, opID int) (*proto.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOperation", ctx, accID, opID)
	ret0, _ := ret[0].(*proto.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOperation indicates an expected call of DeleteOperation.
func (mr *MockFinanceServiceMockRecorder) DeleteOperation(ctx, accID, opID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOperation", reflect.TypeOf((*MockFinanceService)(nil).DeleteOperation), ctx, accID, opID)
}

// GetAccountByID mocks base method.
func (m *MockFinanceService) GetAccountByID(ctx context.Context, userID, accountID int) (*proto.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByID", ctx, userID, accountID)
	ret0, _ := ret[0].(*proto.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByID indicates an expected call of GetAccountByID.
func (mr *MockFinanceServiceMockRecorder) GetAccountByID(ctx, userID, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByID", reflect.TypeOf((*MockFinanceService)(nil).GetAccountByID), ctx, userID, accountID)
}

// GetAccountsByUser mocks base method.
func (m *MockFinanceService) GetAccountsByUser(ctx context.Context, userID int) (*proto.ListAccountsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountsByUser", ctx, userID)
	ret0, _ := ret[0].(*proto.ListAccountsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountsByUser indicates an expected call of GetAccountsByUser.
func (mr *MockFinanceServiceMockRecorder) GetAccountsByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountsByUser", reflect.TypeOf((*MockFinanceService)(nil).GetAccountsByUser), ctx, userID)
}

// GetCategoriesByUser mocks base method.
func (m *MockFinanceService) GetCategoriesByUser(ctx context.Context, userID int) (*proto.ListCategoriesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoriesByUser", ctx, userID)
	ret0, _ := ret[0].(*proto.ListCategoriesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoriesByUser indicates an expected call of GetCategoriesByUser.
func (mr *MockFinanceServiceMockRecorder) GetCategoriesByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoriesByUser", reflect.TypeOf((*MockFinanceService)(nil).GetCategoriesByUser), ctx, userID)
}

// GetCategoriesWithStatsByUser mocks base method.
func (m *MockFinanceService) GetCategoriesWithStatsByUser(ctx context.Context, userID int) (*proto.ListCategoriesWithStatsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoriesWithStatsByUser", ctx, userID)
	ret0, _ := ret[0].(*proto.ListCategoriesWithStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoriesWithStatsByUser indicates an expected call of GetCategoriesWithStatsByUser.
func (mr *MockFinanceServiceMockRecorder) GetCategoriesWithStatsByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoriesWithStatsByUser", reflect.TypeOf((*MockFinanceService)(nil).GetCategoriesWithStatsByUser), ctx, userID)
}

// GetCategoryByID mocks base method.
func (m *MockFinanceService) GetCategoryByID(ctx context.Context, userID, categoryID int) (*proto.CategoryWithStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryByID", ctx, userID, categoryID)
	ret0, _ := ret[0].(*proto.CategoryWithStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryByID indicates an expected call of GetCategoryByID.
func (mr *MockFinanceServiceMockRecorder) GetCategoryByID(ctx, userID, categoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryByID", reflect.TypeOf((*MockFinanceService)(nil).GetCategoryByID), ctx, userID, categoryID)
}

// GetOperationByID mocks base method.
func (m *MockFinanceService) GetOperationByID(ctx context.Context, accID, opID int) (*proto.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperationByID", ctx, accID, opID)
	ret0, _ := ret[0].(*proto.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOperationByID indicates an expected call of GetOperationByID.
func (mr *MockFinanceServiceMockRecorder) GetOperationByID(ctx, accID, opID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperationByID", reflect.TypeOf((*MockFinanceService)(nil).GetOperationByID), ctx, accID, opID)
}

// GetOperationsByAccount mocks base method.
func (m *MockFinanceService) GetOperationsByAccount(ctx context.Context, req []byte) (*proto.ListOperationsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperationsByAccount", ctx, req)
	ret0, _ := ret[0].(*proto.ListOperationsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOperationsByAccount indicates an expected call of GetOperationsByAccount.
func (mr *MockFinanceServiceMockRecorder) GetOperationsByAccount(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperationsByAccount", reflect.TypeOf((*MockFinanceService)(nil).GetOperationsByAccount), ctx, req)
}

// UpdateAccount mocks base method.
func (m *MockFinanceService) UpdateAccount(ctx context.Context, req models.UpdateAccountRequest) (*proto.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccount", ctx, req)
	ret0, _ := ret[0].(*proto.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccount indicates an expected call of UpdateAccount.
func (mr *MockFinanceServiceMockRecorder) UpdateAccount(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccount", reflect.TypeOf((*MockFinanceService)(nil).UpdateAccount), ctx, req)
}

// UpdateCategory mocks base method.
func (m *MockFinanceService) UpdateCategory(ctx context.Context, category models.Category) (*proto.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategory", ctx, category)
	ret0, _ := ret[0].(*proto.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCategory indicates an expected call of UpdateCategory.
func (mr *MockFinanceServiceMockRecorder) UpdateCategory(ctx, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategory", reflect.TypeOf((*MockFinanceService)(nil).UpdateCategory), ctx, category)
}

// UpdateOperation mocks base method.
func (m *MockFinanceService) UpdateOperation(ctx context.Context, req models.UpdateOperationRequest) (*proto.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOperation", ctx, req)
	ret0, _ := ret[0].(*proto.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOperation indicates an expected call of UpdateOperation.
func (mr *MockFinanceServiceMockRecorder) UpdateOperation(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOperation", reflect.TypeOf((*MockFinanceService)(nil).UpdateOperation), ctx, req)
}
