// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2025_2_VKarmane/internal/service/budget (interfaces: BudgetService)
//
// Generated by this command:
//
//	mockgen -destination=mock_budget_service.go -package=mocks github.com/go-park-mail-ru/2025_2_VKarmane/internal/service/budget BudgetService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2025_2_VKarmane/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockBudgetService is a mock of BudgetService interface.
type MockBudgetService struct {
	ctrl     *gomock.Controller
	recorder *MockBudgetServiceMockRecorder
	isgomock struct{}
}

// MockBudgetServiceMockRecorder is the mock recorder for MockBudgetService.
type MockBudgetServiceMockRecorder struct {
	mock *MockBudgetService
}

// NewMockBudgetService creates a new mock instance.
func NewMockBudgetService(ctrl *gomock.Controller) *MockBudgetService {
	mock := &MockBudgetService{ctrl: ctrl}
	mock.recorder = &MockBudgetServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBudgetService) EXPECT() *MockBudgetServiceMockRecorder {
	return m.recorder
}

// GetBudgetByID mocks base method.
func (m *MockBudgetService) GetBudgetByID(ctx context.Context, userID, budgetID int) (models.Budget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBudgetByID", ctx, userID, budgetID)
	ret0, _ := ret[0].(models.Budget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBudgetByID indicates an expected call of GetBudgetByID.
func (mr *MockBudgetServiceMockRecorder) GetBudgetByID(ctx, userID, budgetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBudgetByID", reflect.TypeOf((*MockBudgetService)(nil).GetBudgetByID), ctx, userID, budgetID)
}

// GetBudgetsForUser mocks base method.
func (m *MockBudgetService) GetBudgetsForUser(ctx context.Context, userID int) ([]models.Budget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBudgetsForUser", ctx, userID)
	ret0, _ := ret[0].([]models.Budget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBudgetsForUser indicates an expected call of GetBudgetsForUser.
func (mr *MockBudgetServiceMockRecorder) GetBudgetsForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBudgetsForUser", reflect.TypeOf((*MockBudgetService)(nil).GetBudgetsForUser), ctx, userID)
}
