// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2025_2_VKarmane/internal/handlers/budget (interfaces: BudgetUseCase)
//
// Generated by this command:
//
//	mockgen -destination=mock_budget_usecase.go -package=mocks github.com/go-park-mail-ru/2025_2_VKarmane/internal/handlers/budget BudgetUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2025_2_VKarmane/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockBudgetUseCase is a mock of BudgetUseCase interface.
type MockBudgetUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockBudgetUseCaseMockRecorder
	isgomock struct{}
}

// MockBudgetUseCaseMockRecorder is the mock recorder for MockBudgetUseCase.
type MockBudgetUseCaseMockRecorder struct {
	mock *MockBudgetUseCase
}

// NewMockBudgetUseCase creates a new mock instance.
func NewMockBudgetUseCase(ctrl *gomock.Controller) *MockBudgetUseCase {
	mock := &MockBudgetUseCase{ctrl: ctrl}
	mock.recorder = &MockBudgetUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBudgetUseCase) EXPECT() *MockBudgetUseCaseMockRecorder {
	return m.recorder
}

// GetBudgetByID mocks base method.
func (m *MockBudgetUseCase) GetBudgetByID(ctx context.Context, userID, budgetID int) (models.Budget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBudgetByID", ctx, userID, budgetID)
	ret0, _ := ret[0].(models.Budget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBudgetByID indicates an expected call of GetBudgetByID.
func (mr *MockBudgetUseCaseMockRecorder) GetBudgetByID(ctx, userID, budgetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBudgetByID", reflect.TypeOf((*MockBudgetUseCase)(nil).GetBudgetByID), ctx, userID, budgetID)
}

// GetBudgetsForUser mocks base method.
func (m *MockBudgetUseCase) GetBudgetsForUser(ctx context.Context, userID int) ([]models.Budget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBudgetsForUser", ctx, userID)
	ret0, _ := ret[0].([]models.Budget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBudgetsForUser indicates an expected call of GetBudgetsForUser.
func (mr *MockBudgetUseCaseMockRecorder) GetBudgetsForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBudgetsForUser", reflect.TypeOf((*MockBudgetUseCase)(nil).GetBudgetsForUser), ctx, userID)
}
