// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2025_2_VKarmane/internal/app/finance_service/proto (interfaces: FinanceServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=mock_finance_client.go -package=mocks github.com/go-park-mail-ru/2025_2_VKarmane/internal/app/finance_service/proto FinanceServiceClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	proto "github.com/go-park-mail-ru/2025_2_VKarmane/internal/app/finance_service/proto"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockFinanceServiceClient is a mock of FinanceServiceClient interface.
type MockFinanceServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockFinanceServiceClientMockRecorder
	isgomock struct{}
}

// MockFinanceServiceClientMockRecorder is the mock recorder for MockFinanceServiceClient.
type MockFinanceServiceClientMockRecorder struct {
	mock *MockFinanceServiceClient
}

// NewMockFinanceServiceClient creates a new mock instance.
func NewMockFinanceServiceClient(ctrl *gomock.Controller) *MockFinanceServiceClient {
	mock := &MockFinanceServiceClient{ctrl: ctrl}
	mock.recorder = &MockFinanceServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFinanceServiceClient) EXPECT() *MockFinanceServiceClientMockRecorder {
	return m.recorder
}

// AddUserToAccounnt mocks base method.
func (m *MockFinanceServiceClient) AddUserToAccounnt(ctx context.Context, in *proto.AddToAccountReqeust, opts ...grpc.CallOption) (*proto.SharingsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddUserToAccounnt", varargs...)
	ret0, _ := ret[0].(*proto.SharingsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddUserToAccounnt indicates an expected call of AddUserToAccounnt.
func (mr *MockFinanceServiceClientMockRecorder) AddUserToAccounnt(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserToAccounnt", reflect.TypeOf((*MockFinanceServiceClient)(nil).AddUserToAccounnt), varargs...)
}

// CreateAccount mocks base method.
func (m *MockFinanceServiceClient) CreateAccount(ctx context.Context, in *proto.CreateAccountRequest, opts ...grpc.CallOption) (*proto.Account, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateAccount", varargs...)
	ret0, _ := ret[0].(*proto.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockFinanceServiceClientMockRecorder) CreateAccount(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockFinanceServiceClient)(nil).CreateAccount), varargs...)
}

// CreateCategory mocks base method.
func (m *MockFinanceServiceClient) CreateCategory(ctx context.Context, in *proto.CreateCategoryRequest, opts ...grpc.CallOption) (*proto.Category, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateCategory", varargs...)
	ret0, _ := ret[0].(*proto.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCategory indicates an expected call of CreateCategory.
func (mr *MockFinanceServiceClientMockRecorder) CreateCategory(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockFinanceServiceClient)(nil).CreateCategory), varargs...)
}

// CreateOperation mocks base method.
func (m *MockFinanceServiceClient) CreateOperation(ctx context.Context, in *proto.CreateOperationRequest, opts ...grpc.CallOption) (*proto.Operation, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateOperation", varargs...)
	ret0, _ := ret[0].(*proto.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOperation indicates an expected call of CreateOperation.
func (mr *MockFinanceServiceClientMockRecorder) CreateOperation(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOperation", reflect.TypeOf((*MockFinanceServiceClient)(nil).CreateOperation), varargs...)
}

// DeleteAccount mocks base method.
func (m *MockFinanceServiceClient) DeleteAccount(ctx context.Context, in *proto.AccountRequest, opts ...grpc.CallOption) (*proto.Account, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteAccount", varargs...)
	ret0, _ := ret[0].(*proto.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAccount indicates an expected call of DeleteAccount.
func (mr *MockFinanceServiceClientMockRecorder) DeleteAccount(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccount", reflect.TypeOf((*MockFinanceServiceClient)(nil).DeleteAccount), varargs...)
}

// DeleteCategory mocks base method.
func (m *MockFinanceServiceClient) DeleteCategory(ctx context.Context, in *proto.CategoryRequest, opts ...grpc.CallOption) (*proto.Category, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteCategory", varargs...)
	ret0, _ := ret[0].(*proto.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCategory indicates an expected call of DeleteCategory.
func (mr *MockFinanceServiceClientMockRecorder) DeleteCategory(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategory", reflect.TypeOf((*MockFinanceServiceClient)(nil).DeleteCategory), varargs...)
}

// DeleteOperation mocks base method.
func (m *MockFinanceServiceClient) DeleteOperation(ctx context.Context, in *proto.OperationRequest, opts ...grpc.CallOption) (*proto.Operation, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteOperation", varargs...)
	ret0, _ := ret[0].(*proto.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOperation indicates an expected call of DeleteOperation.
func (mr *MockFinanceServiceClientMockRecorder) DeleteOperation(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOperation", reflect.TypeOf((*MockFinanceServiceClient)(nil).DeleteOperation), varargs...)
}

// GetAccount mocks base method.
func (m *MockFinanceServiceClient) GetAccount(ctx context.Context, in *proto.AccountRequest, opts ...grpc.CallOption) (*proto.Account, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAccount", varargs...)
	ret0, _ := ret[0].(*proto.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockFinanceServiceClientMockRecorder) GetAccount(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockFinanceServiceClient)(nil).GetAccount), varargs...)
}

// GetAccountsByUser mocks base method.
func (m *MockFinanceServiceClient) GetAccountsByUser(ctx context.Context, in *proto.UserID, opts ...grpc.CallOption) (*proto.ListAccountsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAccountsByUser", varargs...)
	ret0, _ := ret[0].(*proto.ListAccountsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountsByUser indicates an expected call of GetAccountsByUser.
func (mr *MockFinanceServiceClientMockRecorder) GetAccountsByUser(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountsByUser", reflect.TypeOf((*MockFinanceServiceClient)(nil).GetAccountsByUser), varargs...)
}

// GetCategoriesByUser mocks base method.
func (m *MockFinanceServiceClient) GetCategoriesByUser(ctx context.Context, in *proto.UserID, opts ...grpc.CallOption) (*proto.ListCategoriesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCategoriesByUser", varargs...)
	ret0, _ := ret[0].(*proto.ListCategoriesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoriesByUser indicates an expected call of GetCategoriesByUser.
func (mr *MockFinanceServiceClientMockRecorder) GetCategoriesByUser(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoriesByUser", reflect.TypeOf((*MockFinanceServiceClient)(nil).GetCategoriesByUser), varargs...)
}

// GetCategoriesReport mocks base method.
func (m *MockFinanceServiceClient) GetCategoriesReport(ctx context.Context, in *proto.CategoryReportRequest, opts ...grpc.CallOption) (*proto.CategoryReportResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCategoriesReport", varargs...)
	ret0, _ := ret[0].(*proto.CategoryReportResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoriesReport indicates an expected call of GetCategoriesReport.
func (mr *MockFinanceServiceClientMockRecorder) GetCategoriesReport(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoriesReport", reflect.TypeOf((*MockFinanceServiceClient)(nil).GetCategoriesReport), varargs...)
}

// GetCategoriesWithStatsByUser mocks base method.
func (m *MockFinanceServiceClient) GetCategoriesWithStatsByUser(ctx context.Context, in *proto.UserID, opts ...grpc.CallOption) (*proto.ListCategoriesWithStatsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCategoriesWithStatsByUser", varargs...)
	ret0, _ := ret[0].(*proto.ListCategoriesWithStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoriesWithStatsByUser indicates an expected call of GetCategoriesWithStatsByUser.
func (mr *MockFinanceServiceClientMockRecorder) GetCategoriesWithStatsByUser(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoriesWithStatsByUser", reflect.TypeOf((*MockFinanceServiceClient)(nil).GetCategoriesWithStatsByUser), varargs...)
}

// GetCategory mocks base method.
func (m *MockFinanceServiceClient) GetCategory(ctx context.Context, in *proto.CategoryRequest, opts ...grpc.CallOption) (*proto.CategoryWithStats, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCategory", varargs...)
	ret0, _ := ret[0].(*proto.CategoryWithStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategory indicates an expected call of GetCategory.
func (mr *MockFinanceServiceClientMockRecorder) GetCategory(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategory", reflect.TypeOf((*MockFinanceServiceClient)(nil).GetCategory), varargs...)
}

// GetCategoryByName mocks base method.
func (m *MockFinanceServiceClient) GetCategoryByName(ctx context.Context, in *proto.CategoryByNameRequest, opts ...grpc.CallOption) (*proto.CategoryWithStats, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCategoryByName", varargs...)
	ret0, _ := ret[0].(*proto.CategoryWithStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryByName indicates an expected call of GetCategoryByName.
func (mr *MockFinanceServiceClientMockRecorder) GetCategoryByName(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryByName", reflect.TypeOf((*MockFinanceServiceClient)(nil).GetCategoryByName), varargs...)
}

// GetOperation mocks base method.
func (m *MockFinanceServiceClient) GetOperation(ctx context.Context, in *proto.OperationRequest, opts ...grpc.CallOption) (*proto.Operation, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOperation", varargs...)
	ret0, _ := ret[0].(*proto.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOperation indicates an expected call of GetOperation.
func (mr *MockFinanceServiceClientMockRecorder) GetOperation(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperation", reflect.TypeOf((*MockFinanceServiceClient)(nil).GetOperation), varargs...)
}

// GetOperationsByAccount mocks base method.
func (m *MockFinanceServiceClient) GetOperationsByAccount(ctx context.Context, in *proto.OperationsByAccountAndFiltersRequest, opts ...grpc.CallOption) (*proto.ListOperationsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOperationsByAccount", varargs...)
	ret0, _ := ret[0].(*proto.ListOperationsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOperationsByAccount indicates an expected call of GetOperationsByAccount.
func (mr *MockFinanceServiceClientMockRecorder) GetOperationsByAccount(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperationsByAccount", reflect.TypeOf((*MockFinanceServiceClient)(nil).GetOperationsByAccount), varargs...)
}

// UpdateAccount mocks base method.
func (m *MockFinanceServiceClient) UpdateAccount(ctx context.Context, in *proto.UpdateAccountRequest, opts ...grpc.CallOption) (*proto.Account, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateAccount", varargs...)
	ret0, _ := ret[0].(*proto.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccount indicates an expected call of UpdateAccount.
func (mr *MockFinanceServiceClientMockRecorder) UpdateAccount(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccount", reflect.TypeOf((*MockFinanceServiceClient)(nil).UpdateAccount), varargs...)
}

// UpdateCategory mocks base method.
func (m *MockFinanceServiceClient) UpdateCategory(ctx context.Context, in *proto.UpdateCategoryRequest, opts ...grpc.CallOption) (*proto.Category, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateCategory", varargs...)
	ret0, _ := ret[0].(*proto.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCategory indicates an expected call of UpdateCategory.
func (mr *MockFinanceServiceClientMockRecorder) UpdateCategory(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategory", reflect.TypeOf((*MockFinanceServiceClient)(nil).UpdateCategory), varargs...)
}

// UpdateOperation mocks base method.
func (m *MockFinanceServiceClient) UpdateOperation(ctx context.Context, in *proto.UpdateOperationRequest, opts ...grpc.CallOption) (*proto.Operation, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateOperation", varargs...)
	ret0, _ := ret[0].(*proto.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOperation indicates an expected call of UpdateOperation.
func (mr *MockFinanceServiceClientMockRecorder) UpdateOperation(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOperation", reflect.TypeOf((*MockFinanceServiceClient)(nil).UpdateOperation), varargs...)
}
