// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2025_2_VKarmane/internal/app/account/handlers (interfaces: BalanceUseCase)
//
// Generated by this command:
//
//	mockgen -destination=mock_balance_usecase.go -package=mocks github.com/go-park-mail-ru/2025_2_VKarmane/internal/app/account/handlers BalanceUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2025_2_VKarmane/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockBalanceUseCase is a mock of BalanceUseCase interface.
type MockBalanceUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceUseCaseMockRecorder
	isgomock struct{}
}

// MockBalanceUseCaseMockRecorder is the mock recorder for MockBalanceUseCase.
type MockBalanceUseCaseMockRecorder struct {
	mock *MockBalanceUseCase
}

// NewMockBalanceUseCase creates a new mock instance.
func NewMockBalanceUseCase(ctrl *gomock.Controller) *MockBalanceUseCase {
	mock := &MockBalanceUseCase{ctrl: ctrl}
	mock.recorder = &MockBalanceUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceUseCase) EXPECT() *MockBalanceUseCaseMockRecorder {
	return m.recorder
}

// CreateAccount mocks base method.
func (m *MockBalanceUseCase) CreateAccount(ctx context.Context, req models.CreateAccountRequest, userID int) (models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", ctx, req, userID)
	ret0, _ := ret[0].(models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockBalanceUseCaseMockRecorder) CreateAccount(ctx, req, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockBalanceUseCase)(nil).CreateAccount), ctx, req, userID)
}

// DeleteAccount mocks base method.
func (m *MockBalanceUseCase) DeleteAccount(ctx context.Context, userID, accID int) (models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccount", ctx, userID, accID)
	ret0, _ := ret[0].(models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAccount indicates an expected call of DeleteAccount.
func (mr *MockBalanceUseCaseMockRecorder) DeleteAccount(ctx, userID, accID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccount", reflect.TypeOf((*MockBalanceUseCase)(nil).DeleteAccount), ctx, userID, accID)
}

// GetAccountByID mocks base method.
func (m *MockBalanceUseCase) GetAccountByID(ctx context.Context, userID, accountID int) (models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByID", ctx, userID, accountID)
	ret0, _ := ret[0].(models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByID indicates an expected call of GetAccountByID.
func (mr *MockBalanceUseCaseMockRecorder) GetAccountByID(ctx, userID, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByID", reflect.TypeOf((*MockBalanceUseCase)(nil).GetAccountByID), ctx, userID, accountID)
}

// GetBalanceForUser mocks base method.
func (m *MockBalanceUseCase) GetBalanceForUser(ctx context.Context, userID int) ([]models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceForUser", ctx, userID)
	ret0, _ := ret[0].([]models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalanceForUser indicates an expected call of GetBalanceForUser.
func (mr *MockBalanceUseCaseMockRecorder) GetBalanceForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceForUser", reflect.TypeOf((*MockBalanceUseCase)(nil).GetBalanceForUser), ctx, userID)
}

// UpdateAccount mocks base method.
func (m *MockBalanceUseCase) UpdateAccount(ctx context.Context, req models.UpdateAccountRequest, userID, accID int) (models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccount", ctx, req, userID, accID)
	ret0, _ := ret[0].(models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccount indicates an expected call of UpdateAccount.
func (mr *MockBalanceUseCaseMockRecorder) UpdateAccount(ctx, req, userID, accID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccount", reflect.TypeOf((*MockBalanceUseCase)(nil).UpdateAccount), ctx, req, userID, accID)
}
