// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2025_2_VKarmane/internal/service/operation (interfaces: OperationService)
//
// Generated by this command:
//
//	mockgen -destination=mock_operation_service.go -package=mocks github.com/go-park-mail-ru/2025_2_VKarmane/internal/service/operation OperationService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2025_2_VKarmane/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockOperationService is a mock of OperationService interface.
type MockOperationService struct {
	ctrl     *gomock.Controller
	recorder *MockOperationServiceMockRecorder
	isgomock struct{}
}

// MockOperationServiceMockRecorder is the mock recorder for MockOperationService.
type MockOperationServiceMockRecorder struct {
	mock *MockOperationService
}

// NewMockOperationService creates a new mock instance.
func NewMockOperationService(ctrl *gomock.Controller) *MockOperationService {
	mock := &MockOperationService{ctrl: ctrl}
	mock.recorder = &MockOperationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOperationService) EXPECT() *MockOperationServiceMockRecorder {
	return m.recorder
}

// CreateOperation mocks base method.
func (m *MockOperationService) CreateOperation(ctx context.Context, req models.CreateOperationRequest, accID int) (models.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOperation", ctx, req, accID)
	ret0, _ := ret[0].(models.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOperation indicates an expected call of CreateOperation.
func (mr *MockOperationServiceMockRecorder) CreateOperation(ctx, req, accID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOperation", reflect.TypeOf((*MockOperationService)(nil).CreateOperation), ctx, req, accID)
}

// DeleteOperation mocks base method.
func (m *MockOperationService) DeleteOperation(ctx context.Context, accID, opID int) (models.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOperation", ctx, accID, opID)
	ret0, _ := ret[0].(models.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOperation indicates an expected call of DeleteOperation.
func (mr *MockOperationServiceMockRecorder) DeleteOperation(ctx, accID, opID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOperation", reflect.TypeOf((*MockOperationService)(nil).DeleteOperation), ctx, accID, opID)
}

// GetAccountOperations mocks base method.
func (m *MockOperationService) GetAccountOperations(ctx context.Context, accID int) ([]models.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountOperations", ctx, accID)
	ret0, _ := ret[0].([]models.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountOperations indicates an expected call of GetAccountOperations.
func (mr *MockOperationServiceMockRecorder) GetAccountOperations(ctx, accID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountOperations", reflect.TypeOf((*MockOperationService)(nil).GetAccountOperations), ctx, accID)
}

// GetOperationByID mocks base method.
func (m *MockOperationService) GetOperationByID(ctx context.Context, accID, opID int) (models.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperationByID", ctx, accID, opID)
	ret0, _ := ret[0].(models.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOperationByID indicates an expected call of GetOperationByID.
func (mr *MockOperationServiceMockRecorder) GetOperationByID(ctx, accID, opID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperationByID", reflect.TypeOf((*MockOperationService)(nil).GetOperationByID), ctx, accID, opID)
}

// UpdateOperation mocks base method.
func (m *MockOperationService) UpdateOperation(ctx context.Context, req models.UpdateOperationRequest, accID, opID int) (models.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOperation", ctx, req, accID, opID)
	ret0, _ := ret[0].(models.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOperation indicates an expected call of UpdateOperation.
func (mr *MockOperationServiceMockRecorder) UpdateOperation(ctx, req, accID, opID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOperation", reflect.TypeOf((*MockOperationService)(nil).UpdateOperation), ctx, req, accID, opID)
}
