// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2025_2_VKarmane/internal/app/finance_service/service (interfaces: FinanceRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock_finance_repository.go -package=mocks github.com/go-park-mail-ru/2025_2_VKarmane/internal/app/finance_service/service FinanceRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2025_2_VKarmane/internal/app/finance_service/models"
	gomock "go.uber.org/mock/gomock"
)

// MockFinanceRepository is a mock of FinanceRepository interface.
type MockFinanceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFinanceRepositoryMockRecorder
	isgomock struct{}
}

// MockFinanceRepositoryMockRecorder is the mock recorder for MockFinanceRepository.
type MockFinanceRepositoryMockRecorder struct {
	mock *MockFinanceRepository
}

// NewMockFinanceRepository creates a new mock instance.
func NewMockFinanceRepository(ctrl *gomock.Controller) *MockFinanceRepository {
	mock := &MockFinanceRepository{ctrl: ctrl}
	mock.recorder = &MockFinanceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFinanceRepository) EXPECT() *MockFinanceRepositoryMockRecorder {
	return m.recorder
}

// AddUserToAccount mocks base method.
func (m *MockFinanceRepository) AddUserToAccount(ctx context.Context, userID, accountID int) (models.SharingAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserToAccount", ctx, userID, accountID)
	ret0, _ := ret[0].(models.SharingAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddUserToAccount indicates an expected call of AddUserToAccount.
func (mr *MockFinanceRepositoryMockRecorder) AddUserToAccount(ctx, userID, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserToAccount", reflect.TypeOf((*MockFinanceRepository)(nil).AddUserToAccount), ctx, userID, accountID)
}

// CreateAccount mocks base method.
func (m *MockFinanceRepository) CreateAccount(ctx context.Context, account models.Account, userID int) (models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", ctx, account, userID)
	ret0, _ := ret[0].(models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockFinanceRepositoryMockRecorder) CreateAccount(ctx, account, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockFinanceRepository)(nil).CreateAccount), ctx, account, userID)
}

// CreateCategory mocks base method.
func (m *MockFinanceRepository) CreateCategory(ctx context.Context, category models.Category) (models.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategory", ctx, category)
	ret0, _ := ret[0].(models.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCategory indicates an expected call of CreateCategory.
func (mr *MockFinanceRepositoryMockRecorder) CreateCategory(ctx, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockFinanceRepository)(nil).CreateCategory), ctx, category)
}

// CreateOperation mocks base method.
func (m *MockFinanceRepository) CreateOperation(ctx context.Context, op models.Operation) (models.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOperation", ctx, op)
	ret0, _ := ret[0].(models.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOperation indicates an expected call of CreateOperation.
func (mr *MockFinanceRepositoryMockRecorder) CreateOperation(ctx, op any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOperation", reflect.TypeOf((*MockFinanceRepository)(nil).CreateOperation), ctx, op)
}

// DeleteAccount mocks base method.
func (m *MockFinanceRepository) DeleteAccount(ctx context.Context, userID, accID int) (models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccount", ctx, userID, accID)
	ret0, _ := ret[0].(models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAccount indicates an expected call of DeleteAccount.
func (mr *MockFinanceRepositoryMockRecorder) DeleteAccount(ctx, userID, accID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccount", reflect.TypeOf((*MockFinanceRepository)(nil).DeleteAccount), ctx, userID, accID)
}

// DeleteCategory mocks base method.
func (m *MockFinanceRepository) DeleteCategory(ctx context.Context, userID, categoryID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategory", ctx, userID, categoryID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCategory indicates an expected call of DeleteCategory.
func (mr *MockFinanceRepositoryMockRecorder) DeleteCategory(ctx, userID, categoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategory", reflect.TypeOf((*MockFinanceRepository)(nil).DeleteCategory), ctx, userID, categoryID)
}

// DeleteOperation mocks base method.
func (m *MockFinanceRepository) DeleteOperation(ctx context.Context, accID, opID int) (models.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOperation", ctx, accID, opID)
	ret0, _ := ret[0].(models.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOperation indicates an expected call of DeleteOperation.
func (mr *MockFinanceRepositoryMockRecorder) DeleteOperation(ctx, accID, opID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOperation", reflect.TypeOf((*MockFinanceRepository)(nil).DeleteOperation), ctx, accID, opID)
}

// GetAccountByID mocks base method.
func (m *MockFinanceRepository) GetAccountByID(ctx context.Context, userID, accountID int) (models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByID", ctx, userID, accountID)
	ret0, _ := ret[0].(models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByID indicates an expected call of GetAccountByID.
func (mr *MockFinanceRepositoryMockRecorder) GetAccountByID(ctx, userID, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByID", reflect.TypeOf((*MockFinanceRepository)(nil).GetAccountByID), ctx, userID, accountID)
}

// GetAccountsByUser mocks base method.
func (m *MockFinanceRepository) GetAccountsByUser(ctx context.Context, userID int) ([]models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountsByUser", ctx, userID)
	ret0, _ := ret[0].([]models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountsByUser indicates an expected call of GetAccountsByUser.
func (mr *MockFinanceRepositoryMockRecorder) GetAccountsByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountsByUser", reflect.TypeOf((*MockFinanceRepository)(nil).GetAccountsByUser), ctx, userID)
}

// GetCategoriesByUser mocks base method.
func (m *MockFinanceRepository) GetCategoriesByUser(ctx context.Context, userID int) ([]models.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoriesByUser", ctx, userID)
	ret0, _ := ret[0].([]models.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoriesByUser indicates an expected call of GetCategoriesByUser.
func (mr *MockFinanceRepositoryMockRecorder) GetCategoriesByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoriesByUser", reflect.TypeOf((*MockFinanceRepository)(nil).GetCategoriesByUser), ctx, userID)
}

// GetCategoriesWithStatsByUser mocks base method.
func (m *MockFinanceRepository) GetCategoriesWithStatsByUser(ctx context.Context, userID int) ([]models.CategoryWithStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoriesWithStatsByUser", ctx, userID)
	ret0, _ := ret[0].([]models.CategoryWithStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoriesWithStatsByUser indicates an expected call of GetCategoriesWithStatsByUser.
func (mr *MockFinanceRepositoryMockRecorder) GetCategoriesWithStatsByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoriesWithStatsByUser", reflect.TypeOf((*MockFinanceRepository)(nil).GetCategoriesWithStatsByUser), ctx, userID)
}

// GetCategoryByID mocks base method.
func (m *MockFinanceRepository) GetCategoryByID(ctx context.Context, userID, categoryID int) (models.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryByID", ctx, userID, categoryID)
	ret0, _ := ret[0].(models.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryByID indicates an expected call of GetCategoryByID.
func (mr *MockFinanceRepositoryMockRecorder) GetCategoryByID(ctx, userID, categoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryByID", reflect.TypeOf((*MockFinanceRepository)(nil).GetCategoryByID), ctx, userID, categoryID)
}

// GetCategoryByName mocks base method.
func (m *MockFinanceRepository) GetCategoryByName(ctx context.Context, userID int, categoryName string) (models.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryByName", ctx, userID, categoryName)
	ret0, _ := ret[0].(models.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryByName indicates an expected call of GetCategoryByName.
func (mr *MockFinanceRepositoryMockRecorder) GetCategoryByName(ctx, userID, categoryName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryByName", reflect.TypeOf((*MockFinanceRepository)(nil).GetCategoryByName), ctx, userID, categoryName)
}

// GetCategoryStats mocks base method.
func (m *MockFinanceRepository) GetCategoryStats(ctx context.Context, userID, categoryID int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryStats", ctx, userID, categoryID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryStats indicates an expected call of GetCategoryStats.
func (mr *MockFinanceRepositoryMockRecorder) GetCategoryStats(ctx, userID, categoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryStats", reflect.TypeOf((*MockFinanceRepository)(nil).GetCategoryStats), ctx, userID, categoryID)
}

// GetOperationByID mocks base method.
func (m *MockFinanceRepository) GetOperationByID(ctx context.Context, accID, opID int) (models.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperationByID", ctx, accID, opID)
	ret0, _ := ret[0].(models.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOperationByID indicates an expected call of GetOperationByID.
func (mr *MockFinanceRepositoryMockRecorder) GetOperationByID(ctx, accID, opID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperationByID", reflect.TypeOf((*MockFinanceRepository)(nil).GetOperationByID), ctx, accID, opID)
}

// GetOperationsByAccount mocks base method.
func (m *MockFinanceRepository) GetOperationsByAccount(ctx context.Context, accountID int) ([]models.OperationInList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOperationsByAccount", ctx, accountID)
	ret0, _ := ret[0].([]models.OperationInList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOperationsByAccount indicates an expected call of GetOperationsByAccount.
func (mr *MockFinanceRepositoryMockRecorder) GetOperationsByAccount(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOperationsByAccount", reflect.TypeOf((*MockFinanceRepository)(nil).GetOperationsByAccount), ctx, accountID)
}

// UpdateAccount mocks base method.
func (m *MockFinanceRepository) UpdateAccount(ctx context.Context, req models.UpdateAccountRequest) (models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccount", ctx, req)
	ret0, _ := ret[0].(models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccount indicates an expected call of UpdateAccount.
func (mr *MockFinanceRepositoryMockRecorder) UpdateAccount(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccount", reflect.TypeOf((*MockFinanceRepository)(nil).UpdateAccount), ctx, req)
}

// UpdateAccountBalance mocks base method.
func (m *MockFinanceRepository) UpdateAccountBalance(ctx context.Context, accountID int, newBalance float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccountBalance", ctx, accountID, newBalance)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAccountBalance indicates an expected call of UpdateAccountBalance.
func (mr *MockFinanceRepositoryMockRecorder) UpdateAccountBalance(ctx, accountID, newBalance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccountBalance", reflect.TypeOf((*MockFinanceRepository)(nil).UpdateAccountBalance), ctx, accountID, newBalance)
}

// UpdateCategory mocks base method.
func (m *MockFinanceRepository) UpdateCategory(ctx context.Context, category models.Category) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategory", ctx, category)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCategory indicates an expected call of UpdateCategory.
func (mr *MockFinanceRepositoryMockRecorder) UpdateCategory(ctx, category any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategory", reflect.TypeOf((*MockFinanceRepository)(nil).UpdateCategory), ctx, category)
}

// UpdateOperation mocks base method.
func (m *MockFinanceRepository) UpdateOperation(ctx context.Context, req models.UpdateOperationRequest, accID, opID int) (models.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOperation", ctx, req, accID, opID)
	ret0, _ := ret[0].(models.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOperation indicates an expected call of UpdateOperation.
func (mr *MockFinanceRepositoryMockRecorder) UpdateOperation(ctx, req, accID, opID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOperation", reflect.TypeOf((*MockFinanceRepository)(nil).UpdateOperation), ctx, req, accID, opID)
}
