// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson59429d10DecodeGithubComGoParkMailRu20252VKarmaneInternalAppFinanceServiceModels(in *jlexer.Lexer, out *ElasticsearchResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "hits":
			easyjson59429d10Decode(in, &out.Hits)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson59429d10EncodeGithubComGoParkMailRu20252VKarmaneInternalAppFinanceServiceModels(out *jwriter.Writer, in ElasticsearchResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"hits\":"
		out.RawString(prefix[1:])
		easyjson59429d10Encode(out, in.Hits)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ElasticsearchResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson59429d10EncodeGithubComGoParkMailRu20252VKarmaneInternalAppFinanceServiceModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ElasticsearchResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson59429d10EncodeGithubComGoParkMailRu20252VKarmaneInternalAppFinanceServiceModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ElasticsearchResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson59429d10DecodeGithubComGoParkMailRu20252VKarmaneInternalAppFinanceServiceModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ElasticsearchResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson59429d10DecodeGithubComGoParkMailRu20252VKarmaneInternalAppFinanceServiceModels(l, v)
}
func easyjson59429d10Decode(in *jlexer.Lexer, out *struct {
	Hits []struct {
		Source ESHitSource `json:"_source"`
	} `json:"hits"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "hits":
			if in.IsNull() {
				in.Skip()
				out.Hits = nil
			} else {
				in.Delim('[')
				if out.Hits == nil {
					if !in.IsDelim(']') {
						out.Hits = make([]struct {
							Source ESHitSource `json:"_source"`
						}, 0, 0)
					} else {
						out.Hits = []struct {
							Source ESHitSource `json:"_source"`
						}{}
					}
				} else {
					out.Hits = (out.Hits)[:0]
				}
				for !in.IsDelim(']') {
					var v1 struct {
						Source ESHitSource `json:"_source"`
					}
					easyjson59429d10Decode1(in, &v1)
					out.Hits = append(out.Hits, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson59429d10Encode(out *jwriter.Writer, in struct {
	Hits []struct {
		Source ESHitSource `json:"_source"`
	} `json:"hits"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"hits\":"
		out.RawString(prefix[1:])
		if in.Hits == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Hits {
				if v2 > 0 {
					out.RawByte(',')
				}
				easyjson59429d10Encode1(out, v3)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}
func easyjson59429d10Decode1(in *jlexer.Lexer, out *struct {
	Source ESHitSource `json:"_source"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "_source":
			(out.Source).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson59429d10Encode1(out *jwriter.Writer, in struct {
	Source ESHitSource `json:"_source"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"_source\":"
		out.RawString(prefix[1:])
		(in.Source).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}
func easyjson59429d10DecodeGithubComGoParkMailRu20252VKarmaneInternalAppFinanceServiceModels1(in *jlexer.Lexer, out *ESHitSource) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int32(in.Int32())
		case "account_id":
			out.AccountID = int32(in.Int32())
		case "category_id":
			out.CategoryID = int32(in.Int32())
		case "category_name":
			out.CategoryName = string(in.String())
		case "type":
			out.Type = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "name":
			out.Name = string(in.String())
		case "category_logo_hashed_id":
			out.CategoryLogoHashedId = string(in.String())
		case "category_logo":
			out.CategoryLogo = string(in.String())
		case "sum":
			out.Sum = float64(in.Float64())
		case "account_type":
			out.AccountType = string(in.String())
		case "curerncy":
			out.CurrencyId = int32(in.Int32())
		case "created_at":
			out.CreatedAt = string(in.String())
		case "date":
			out.Date = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson59429d10EncodeGithubComGoParkMailRu20252VKarmaneInternalAppFinanceServiceModels1(out *jwriter.Writer, in ESHitSource) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int32(int32(in.ID))
	}
	{
		const prefix string = ",\"account_id\":"
		out.RawString(prefix)
		out.Int32(int32(in.AccountID))
	}
	{
		const prefix string = ",\"category_id\":"
		out.RawString(prefix)
		out.Int32(int32(in.CategoryID))
	}
	{
		const prefix string = ",\"category_name\":"
		out.RawString(prefix)
		out.String(string(in.CategoryName))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"category_logo_hashed_id\":"
		out.RawString(prefix)
		out.String(string(in.CategoryLogoHashedId))
	}
	{
		const prefix string = ",\"category_logo\":"
		out.RawString(prefix)
		out.String(string(in.CategoryLogo))
	}
	{
		const prefix string = ",\"sum\":"
		out.RawString(prefix)
		out.Float64(float64(in.Sum))
	}
	{
		const prefix string = ",\"account_type\":"
		out.RawString(prefix)
		out.String(string(in.AccountType))
	}
	{
		const prefix string = ",\"curerncy\":"
		out.RawString(prefix)
		out.Int32(int32(in.CurrencyId))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.String(string(in.CreatedAt))
	}
	{
		const prefix string = ",\"date\":"
		out.RawString(prefix)
		out.String(string(in.Date))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ESHitSource) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson59429d10EncodeGithubComGoParkMailRu20252VKarmaneInternalAppFinanceServiceModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ESHitSource) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson59429d10EncodeGithubComGoParkMailRu20252VKarmaneInternalAppFinanceServiceModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ESHitSource) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson59429d10DecodeGithubComGoParkMailRu20252VKarmaneInternalAppFinanceServiceModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ESHitSource) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson59429d10DecodeGithubComGoParkMailRu20252VKarmaneInternalAppFinanceServiceModels1(l, v)
}
