// Code generated by mockery v2.53.5. DO NOT EDIT.

package budget

import (
	models "github.com/go-park-mail-ru/2025_2_VKarmane/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockBudgetRepository is an autogenerated mock type for the BudgetRepository type
type MockBudgetRepository struct {
	mock.Mock
}

// GetBudgetsByUser provides a mock function with given fields: userID
func (_m *MockBudgetRepository) GetBudgetsByUser(userID int) []models.Budget {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBudgetsByUser")
	}

	var r0 []models.Budget
	if rf, ok := ret.Get(0).(func(int) []models.Budget); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Budget)
		}
	}

	return r0
}

// NewMockBudgetRepository creates a new instance of MockBudgetRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBudgetRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBudgetRepository {
	mock := &MockBudgetRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
