// Code generated by mockery v2.53.5. DO NOT EDIT.

package budget

import (
	models "github.com/go-park-mail-ru/2025_2_VKarmane/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockOperationRepository is an autogenerated mock type for the OperationRepository type
type MockOperationRepository struct {
	mock.Mock
}

// GetOperationsByAccount provides a mock function with given fields: accountID
func (_m *MockOperationRepository) GetOperationsByAccount(accountID int) []models.Operation {
	ret := _m.Called(accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetOperationsByAccount")
	}

	var r0 []models.Operation
	if rf, ok := ret.Get(0).(func(int) []models.Operation); ok {
		r0 = rf(accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Operation)
		}
	}

	return r0
}

// NewMockOperationRepository creates a new instance of MockOperationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOperationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOperationRepository {
	mock := &MockOperationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
