// Code generated by mockery v2.53.5. DO NOT EDIT.

package balance

import (
	models "github.com/go-park-mail-ru/2025_2_VKarmane/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockAccountRepository is an autogenerated mock type for the AccountRepository type
type MockAccountRepository struct {
	mock.Mock
}

// GetAccountsByUser provides a mock function with given fields: userID
func (_m *MockAccountRepository) GetAccountsByUser(userID int) []models.Account {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAccountsByUser")
	}

	var r0 []models.Account
	if rf, ok := ret.Get(0).(func(int) []models.Account); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Account)
		}
	}

	return r0
}

// NewMockAccountRepository creates a new instance of MockAccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountRepository {
	mock := &MockAccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
