// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: internal/app/finance_service/proto/finance.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CurrencyId    int32                  `protobuf:"varint,6,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_internal_app_finance_service_proto_finance_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Account) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Account) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Account) GetCurrencyId() int32 {
	if x != nil {
		return x.CurrencyId
	}
	return 0
}

func (x *Account) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Account) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Description   *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	CurrencyId    int32                  `protobuf:"varint,6,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_finance_service_proto_finance_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateAccountRequest) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *CreateAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAccountRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateAccountRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateAccountRequest) GetCurrencyId() int32 {
	if x != nil {
		return x.CurrencyId
	}
	return 0
}

type UpdateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountId     int32                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Balance       *float64               `protobuf:"fixed64,3,opt,name=balance,proto3,oneof" json:"balance,omitempty"`
	Name          *string                `protobuf:"bytes,4,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountRequest) Reset() {
	*x = UpdateAccountRequest{}
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountRequest) ProtoMessage() {}

func (x *UpdateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_finance_service_proto_finance_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateAccountRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateAccountRequest) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *UpdateAccountRequest) GetBalance() float64 {
	if x != nil && x.Balance != nil {
		return *x.Balance
	}
	return 0
}

func (x *UpdateAccountRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateAccountRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type AccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountId     int32                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountRequest) Reset() {
	*x = AccountRequest{}
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRequest) ProtoMessage() {}

func (x *AccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRequest.ProtoReflect.Descriptor instead.
func (*AccountRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_finance_service_proto_finance_proto_rawDescGZIP(), []int{3}
}

func (x *AccountRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AccountRequest) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type UserID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserID) Reset() {
	*x = UserID{}
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserID) ProtoMessage() {}

func (x *UserID) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserID.ProtoReflect.Descriptor instead.
func (*UserID) Descriptor() ([]byte, []int) {
	return file_internal_app_finance_service_proto_finance_proto_rawDescGZIP(), []int{4}
}

func (x *UserID) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsResponse) Reset() {
	*x = ListAccountsResponse{}
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsResponse) ProtoMessage() {}

func (x *ListAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsResponse.ProtoReflect.Descriptor instead.
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_finance_service_proto_finance_proto_rawDescGZIP(), []int{5}
}

func (x *ListAccountsResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type Operation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     int32                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CategoryId    int32                  `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName  string                 `protobuf:"bytes,4,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	ReceiptUrl    string                 `protobuf:"bytes,8,opt,name=receipt_url,json=receiptUrl,proto3" json:"receipt_url,omitempty"`
	Name          string                 `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	Sum           float64                `protobuf:"fixed64,10,opt,name=sum,proto3" json:"sum,omitempty"`
	CurrencyId    int32                  `protobuf:"varint,11,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	AccountType   string                 `protobuf:"bytes,12,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_internal_app_finance_service_proto_finance_proto_rawDescGZIP(), []int{6}
}

func (x *Operation) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Operation) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *Operation) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Operation) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *Operation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Operation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Operation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Operation) GetReceiptUrl() string {
	if x != nil {
		return x.ReceiptUrl
	}
	return ""
}

func (x *Operation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Operation) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *Operation) GetCurrencyId() int32 {
	if x != nil {
		return x.CurrencyId
	}
	return 0
}

func (x *Operation) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *Operation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Operation) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type OperationInList struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId            int32                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CategoryId           int32                  `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName         string                 `protobuf:"bytes,4,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Type                 string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Description          string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Name                 string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	CategoryLogoHashedId string                 `protobuf:"bytes,8,opt,name=category_logo_hashed_id,json=categoryLogoHashedId,proto3" json:"category_logo_hashed_id,omitempty"`
	CategoryLogo         string                 `protobuf:"bytes,9,opt,name=category_logo,json=categoryLogo,proto3" json:"category_logo,omitempty"`
	Sum                  float64                `protobuf:"fixed64,10,opt,name=sum,proto3" json:"sum,omitempty"`
	CurrencyId           int32                  `protobuf:"varint,11,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	AccountType          string                 `protobuf:"bytes,12,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Date                 *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *OperationInList) Reset() {
	*x = OperationInList{}
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationInList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationInList) ProtoMessage() {}

func (x *OperationInList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationInList.ProtoReflect.Descriptor instead.
func (*OperationInList) Descriptor() ([]byte, []int) {
	return file_internal_app_finance_service_proto_finance_proto_rawDescGZIP(), []int{7}
}

func (x *OperationInList) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OperationInList) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *OperationInList) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *OperationInList) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *OperationInList) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OperationInList) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *OperationInList) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OperationInList) GetCategoryLogoHashedId() string {
	if x != nil {
		return x.CategoryLogoHashedId
	}
	return ""
}

func (x *OperationInList) GetCategoryLogo() string {
	if x != nil {
		return x.CategoryLogo
	}
	return ""
}

func (x *OperationInList) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *OperationInList) GetCurrencyId() int32 {
	if x != nil {
		return x.CurrencyId
	}
	return 0
}

func (x *OperationInList) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *OperationInList) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OperationInList) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type CreateOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountId     int32                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CategoryId    *int32                 `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Sum           float64                `protobuf:"fixed64,7,opt,name=sum,proto3" json:"sum,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=date,proto3,oneof" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOperationRequest) Reset() {
	*x = CreateOperationRequest{}
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOperationRequest) ProtoMessage() {}

func (x *CreateOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOperationRequest.ProtoReflect.Descriptor instead.
func (*CreateOperationRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_finance_service_proto_finance_proto_rawDescGZIP(), []int{8}
}

func (x *CreateOperationRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOperationRequest) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateOperationRequest) GetCategoryId() int32 {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return 0
}

func (x *CreateOperationRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateOperationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOperationRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateOperationRequest) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *CreateOperationRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type UpdateOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountId     int32                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	OperationId   int32                  `protobuf:"varint,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	CategoryId    *int32                 `protobuf:"varint,4,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	Name          *string                `protobuf:"bytes,5,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Sum           *float64               `protobuf:"fixed64,7,opt,name=sum,proto3,oneof" json:"sum,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOperationRequest) Reset() {
	*x = UpdateOperationRequest{}
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOperationRequest) ProtoMessage() {}

func (x *UpdateOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOperationRequest.ProtoReflect.Descriptor instead.
func (*UpdateOperationRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_finance_service_proto_finance_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateOperationRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateOperationRequest) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *UpdateOperationRequest) GetOperationId() int32 {
	if x != nil {
		return x.OperationId
	}
	return 0
}

func (x *UpdateOperationRequest) GetCategoryId() int32 {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return 0
}

func (x *UpdateOperationRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateOperationRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateOperationRequest) GetSum() float64 {
	if x != nil && x.Sum != nil {
		return *x.Sum
	}
	return 0
}

func (x *UpdateOperationRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type OperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountId     int32                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	OperationId   int32                  `protobuf:"varint,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationRequest) Reset() {
	*x = OperationRequest{}
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRequest) ProtoMessage() {}

func (x *OperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRequest.ProtoReflect.Descriptor instead.
func (*OperationRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_finance_service_proto_finance_proto_rawDescGZIP(), []int{10}
}

func (x *OperationRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OperationRequest) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *OperationRequest) GetOperationId() int32 {
	if x != nil {
		return x.OperationId
	}
	return 0
}

type ListOperationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []*OperationInList     `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationsResponse) Reset() {
	*x = ListOperationsResponse{}
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationsResponse) ProtoMessage() {}

func (x *ListOperationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationsResponse.ProtoReflect.Descriptor instead.
func (*ListOperationsResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_finance_service_proto_finance_proto_rawDescGZIP(), []int{11}
}

func (x *ListOperationsResponse) GetOperations() []*OperationInList {
	if x != nil {
		return x.Operations
	}
	return nil
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	LogoHashedId  string                 `protobuf:"bytes,5,opt,name=logo_hashed_id,json=logoHashedId,proto3" json:"logo_hashed_id,omitempty"`
	LogoUrl       string                 `protobuf:"bytes,6,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_internal_app_finance_service_proto_finance_proto_rawDescGZIP(), []int{12}
}

func (x *Category) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Category) GetLogoHashedId() string {
	if x != nil {
		return x.LogoHashedId
	}
	return ""
}

func (x *Category) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *Category) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Category) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	LogoHashedId  string                 `protobuf:"bytes,4,opt,name=logo_hashed_id,json=logoHashedId,proto3" json:"logo_hashed_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryRequest) Reset() {
	*x = CreateCategoryRequest{}
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryRequest) ProtoMessage() {}

func (x *CreateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_finance_service_proto_finance_proto_rawDescGZIP(), []int{13}
}

func (x *CreateCategoryRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCategoryRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCategoryRequest) GetLogoHashedId() string {
	if x != nil {
		return x.LogoHashedId
	}
	return ""
}

type UpdateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CategoryId    int32                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	LogoHashedId  *string                `protobuf:"bytes,5,opt,name=logo_hashed_id,json=logoHashedId,proto3,oneof" json:"logo_hashed_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryRequest) Reset() {
	*x = UpdateCategoryRequest{}
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryRequest) ProtoMessage() {}

func (x *UpdateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_finance_service_proto_finance_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateCategoryRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateCategoryRequest) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *UpdateCategoryRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateCategoryRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateCategoryRequest) GetLogoHashedId() string {
	if x != nil && x.LogoHashedId != nil {
		return *x.LogoHashedId
	}
	return ""
}

type CategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CategoryId    int32                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryRequest) Reset() {
	*x = CategoryRequest{}
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryRequest) ProtoMessage() {}

func (x *CategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryRequest.ProtoReflect.Descriptor instead.
func (*CategoryRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_finance_service_proto_finance_proto_rawDescGZIP(), []int{15}
}

func (x *CategoryRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CategoryRequest) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type CategoryByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CategoryName  string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryByNameRequest) Reset() {
	*x = CategoryByNameRequest{}
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryByNameRequest) ProtoMessage() {}

func (x *CategoryByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryByNameRequest.ProtoReflect.Descriptor instead.
func (*CategoryByNameRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_finance_service_proto_finance_proto_rawDescGZIP(), []int{16}
}

func (x *CategoryByNameRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CategoryByNameRequest) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

type ListCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesResponse) Reset() {
	*x = ListCategoriesResponse{}
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesResponse) ProtoMessage() {}

func (x *ListCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_finance_service_proto_finance_proto_rawDescGZIP(), []int{17}
}

func (x *ListCategoriesResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

type CategoryWithStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Category        *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	OperationsCount int32                  `protobuf:"varint,2,opt,name=operations_count,json=operationsCount,proto3" json:"operations_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CategoryWithStats) Reset() {
	*x = CategoryWithStats{}
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryWithStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryWithStats) ProtoMessage() {}

func (x *CategoryWithStats) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryWithStats.ProtoReflect.Descriptor instead.
func (*CategoryWithStats) Descriptor() ([]byte, []int) {
	return file_internal_app_finance_service_proto_finance_proto_rawDescGZIP(), []int{18}
}

func (x *CategoryWithStats) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *CategoryWithStats) GetOperationsCount() int32 {
	if x != nil {
		return x.OperationsCount
	}
	return 0
}

type ListCategoriesWithStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*CategoryWithStats   `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesWithStatsResponse) Reset() {
	*x = ListCategoriesWithStatsResponse{}
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesWithStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesWithStatsResponse) ProtoMessage() {}

func (x *ListCategoriesWithStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesWithStatsResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesWithStatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_finance_service_proto_finance_proto_rawDescGZIP(), []int{19}
}

func (x *ListCategoriesWithStatsResponse) GetCategories() []*CategoryWithStats {
	if x != nil {
		return x.Categories
	}
	return nil
}

type CategoryReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryReportRequest) Reset() {
	*x = CategoryReportRequest{}
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryReportRequest) ProtoMessage() {}

func (x *CategoryReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryReportRequest.ProtoReflect.Descriptor instead.
func (*CategoryReportRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_finance_service_proto_finance_proto_rawDescGZIP(), []int{20}
}

func (x *CategoryReportRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CategoryReportRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *CategoryReportRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type CategoryInReport struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CategoryId      int32                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName    string                 `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	OperationsCount int32                  `protobuf:"varint,3,opt,name=operations_count,json=operationsCount,proto3" json:"operations_count,omitempty"`
	TotalSum        float64                `protobuf:"fixed64,4,opt,name=total_sum,json=totalSum,proto3" json:"total_sum,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CategoryInReport) Reset() {
	*x = CategoryInReport{}
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryInReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryInReport) ProtoMessage() {}

func (x *CategoryInReport) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryInReport.ProtoReflect.Descriptor instead.
func (*CategoryInReport) Descriptor() ([]byte, []int) {
	return file_internal_app_finance_service_proto_finance_proto_rawDescGZIP(), []int{21}
}

func (x *CategoryInReport) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CategoryInReport) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *CategoryInReport) GetOperationsCount() int32 {
	if x != nil {
		return x.OperationsCount
	}
	return 0
}

func (x *CategoryInReport) GetTotalSum() float64 {
	if x != nil {
		return x.TotalSum
	}
	return 0
}

type CategoryReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*CategoryInReport    `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryReportResponse) Reset() {
	*x = CategoryReportResponse{}
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryReportResponse) ProtoMessage() {}

func (x *CategoryReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryReportResponse.ProtoReflect.Descriptor instead.
func (*CategoryReportResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_finance_service_proto_finance_proto_rawDescGZIP(), []int{22}
}

func (x *CategoryReportResponse) GetCategories() []*CategoryInReport {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *CategoryReportResponse) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *CategoryReportResponse) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type OperationsByAccountAndFiltersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountId     int32                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	OperationId   int32                  `protobuf:"varint,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	CategoryIds   []int32                `protobuf:"varint,5,rep,packed,name=category_ids,json=categoryIds,proto3" json:"category_ids,omitempty"`
	OperationType string                 `protobuf:"bytes,6,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
	AccountType   string                 `protobuf:"bytes,7,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationsByAccountAndFiltersRequest) Reset() {
	*x = OperationsByAccountAndFiltersRequest{}
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationsByAccountAndFiltersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationsByAccountAndFiltersRequest) ProtoMessage() {}

func (x *OperationsByAccountAndFiltersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationsByAccountAndFiltersRequest.ProtoReflect.Descriptor instead.
func (*OperationsByAccountAndFiltersRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_finance_service_proto_finance_proto_rawDescGZIP(), []int{23}
}

func (x *OperationsByAccountAndFiltersRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OperationsByAccountAndFiltersRequest) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *OperationsByAccountAndFiltersRequest) GetOperationId() int32 {
	if x != nil {
		return x.OperationId
	}
	return 0
}

func (x *OperationsByAccountAndFiltersRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OperationsByAccountAndFiltersRequest) GetCategoryIds() []int32 {
	if x != nil {
		return x.CategoryIds
	}
	return nil
}

func (x *OperationsByAccountAndFiltersRequest) GetOperationType() string {
	if x != nil {
		return x.OperationType
	}
	return ""
}

func (x *OperationsByAccountAndFiltersRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *OperationsByAccountAndFiltersRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type SharingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SharingId     int32                  `protobuf:"varint,1,opt,name=sharing_id,json=sharingId,proto3" json:"sharing_id,omitempty"`
	AccountId     int32                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	UserId        int32                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SharingsResponse) Reset() {
	*x = SharingsResponse{}
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SharingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharingsResponse) ProtoMessage() {}

func (x *SharingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_finance_service_proto_finance_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharingsResponse.ProtoReflect.Descriptor instead.
func (*SharingsResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_finance_service_proto_finance_proto_rawDescGZIP(), []int{24}
}

func (x *SharingsResponse) GetSharingId() int32 {
	if x != nil {
		return x.SharingId
	}
	return 0
}

func (x *SharingsResponse) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *SharingsResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SharingsResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_internal_app_finance_service_proto_finance_proto protoreflect.FileDescriptor

const file_internal_app_finance_service_proto_finance_proto_rawDesc = "" +
	"\n" +
	"0internal/app/finance_service/proto/finance.proto\x12\afinance\x1a\x1fgoogle/protobuf/timestamp.proto\"\x94\x02\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1f\n" +
	"\vcurrency_id\x18\x06 \x01(\x05R\n" +
	"currencyId\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc9\x01\n" +
	"\x14CreateAccountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1f\n" +
	"\vcurrency_id\x18\x06 \x01(\x05R\n" +
	"currencyIdB\x0e\n" +
	"\f_description\"\xd2\x01\n" +
	"\x14UpdateAccountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x05R\taccountId\x12\x1d\n" +
	"\abalance\x18\x03 \x01(\x01H\x00R\abalance\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x04 \x01(\tH\x01R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x02R\vdescription\x88\x01\x01B\n" +
	"\n" +
	"\b_balanceB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_description\"H\n" +
	"\x0eAccountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x05R\taccountId\"!\n" +
	"\x06UserID\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"D\n" +
	"\x14ListAccountsResponse\x12,\n" +
	"\baccounts\x18\x01 \x03(\v2\x10.finance.AccountR\baccounts\"\xc4\x03\n" +
	"\tOperation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x05R\taccountId\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x05R\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\x04 \x01(\tR\fcategoryName\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1f\n" +
	"\vreceipt_url\x18\b \x01(\tR\n" +
	"receiptUrl\x12\x12\n" +
	"\x04name\x18\t \x01(\tR\x04name\x12\x10\n" +
	"\x03sum\x18\n" +
	" \x01(\x01R\x03sum\x12\x1f\n" +
	"\vcurrency_id\x18\v \x01(\x05R\n" +
	"currencyId\x12!\n" +
	"\faccount_type\x18\f \x01(\tR\vaccountType\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12.\n" +
	"\x04date\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\x04date\"\xed\x03\n" +
	"\x0fOperationInList\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x05R\taccountId\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x05R\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\x04 \x01(\tR\fcategoryName\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x125\n" +
	"\x17category_logo_hashed_id\x18\b \x01(\tR\x14categoryLogoHashedId\x12#\n" +
	"\rcategory_logo\x18\t \x01(\tR\fcategoryLogo\x12\x10\n" +
	"\x03sum\x18\n" +
	" \x01(\x01R\x03sum\x12\x1f\n" +
	"\vcurrency_id\x18\v \x01(\x05R\n" +
	"currencyId\x12!\n" +
	"\faccount_type\x18\f \x01(\tR\vaccountType\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12.\n" +
	"\x04date\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\x04date\"\xa0\x02\n" +
	"\x16CreateOperationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x05R\taccountId\x12$\n" +
	"\vcategory_id\x18\x03 \x01(\x05H\x00R\n" +
	"categoryId\x88\x01\x01\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x10\n" +
	"\x03sum\x18\a \x01(\x01R\x03sum\x123\n" +
	"\x04date\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x04date\x88\x01\x01B\x0e\n" +
	"\f_category_idB\a\n" +
	"\x05_date\"\xf0\x02\n" +
	"\x16UpdateOperationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x05R\taccountId\x12!\n" +
	"\foperation_id\x18\x03 \x01(\x05R\voperationId\x12$\n" +
	"\vcategory_id\x18\x04 \x01(\x05H\x00R\n" +
	"categoryId\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x05 \x01(\tH\x01R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x06 \x01(\tH\x02R\vdescription\x88\x01\x01\x12\x15\n" +
	"\x03sum\x18\a \x01(\x01H\x03R\x03sum\x88\x01\x01\x12>\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x04R\tcreatedAt\x88\x01\x01B\x0e\n" +
	"\f_category_idB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\x06\n" +
	"\x04_sumB\r\n" +
	"\v_created_at\"m\n" +
	"\x10OperationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x05R\taccountId\x12!\n" +
	"\foperation_id\x18\x03 \x01(\x05R\voperationId\"R\n" +
	"\x16ListOperationsResponse\x128\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2\x18.finance.OperationInListR\n" +
	"operations\"\xa0\x02\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12$\n" +
	"\x0elogo_hashed_id\x18\x05 \x01(\tR\flogoHashedId\x12\x19\n" +
	"\blogo_url\x18\x06 \x01(\tR\alogoUrl\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8c\x01\n" +
	"\x15CreateCategoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12$\n" +
	"\x0elogo_hashed_id\x18\x04 \x01(\tR\flogoHashedId\"\xe8\x01\n" +
	"\x15UpdateCategoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x05R\n" +
	"categoryId\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12)\n" +
	"\x0elogo_hashed_id\x18\x05 \x01(\tH\x02R\flogoHashedId\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\x11\n" +
	"\x0f_logo_hashed_id\"K\n" +
	"\x0fCategoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x05R\n" +
	"categoryId\"U\n" +
	"\x15CategoryByNameRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\"K\n" +
	"\x16ListCategoriesResponse\x121\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x11.finance.CategoryR\n" +
	"categories\"m\n" +
	"\x11CategoryWithStats\x12-\n" +
	"\bcategory\x18\x01 \x01(\v2\x11.finance.CategoryR\bcategory\x12)\n" +
	"\x10operations_count\x18\x02 \x01(\x05R\x0foperationsCount\"]\n" +
	"\x1fListCategoriesWithStatsResponse\x12:\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x1a.finance.CategoryWithStatsR\n" +
	"categories\"\x90\x01\n" +
	"\x15CategoryReportRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x120\n" +
	"\x05start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\"\xa0\x01\n" +
	"\x10CategoryInReport\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x05R\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\x02 \x01(\tR\fcategoryName\x12)\n" +
	"\x10operations_count\x18\x03 \x01(\x05R\x0foperationsCount\x12\x1b\n" +
	"\ttotal_sum\x18\x04 \x01(\x01R\btotalSum\"\xb3\x01\n" +
	"\x16CategoryReportResponse\x129\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x19.finance.CategoryInReportR\n" +
	"categories\x120\n" +
	"\x05start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\"\xb2\x02\n" +
	"$OperationsByAccountAndFiltersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x05R\taccountId\x12!\n" +
	"\foperation_id\x18\x03 \x01(\x05R\voperationId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12!\n" +
	"\fcategory_ids\x18\x05 \x03(\x05R\vcategoryIds\x12%\n" +
	"\x0eoperation_type\x18\x06 \x01(\tR\roperationType\x12!\n" +
	"\faccount_type\x18\a \x01(\tR\vaccountType\x12.\n" +
	"\x04date\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x04date\"\xa4\x01\n" +
	"\x10SharingsResponse\x12\x1d\n" +
	"\n" +
	"sharing_id\x18\x01 \x01(\x05R\tsharingId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x05R\taccountId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x05R\x06userId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\xed\n" +
	"\n" +
	"\x0eFinanceService\x12@\n" +
	"\rCreateAccount\x12\x1d.finance.CreateAccountRequest\x1a\x10.finance.Account\x127\n" +
	"\n" +
	"GetAccount\x12\x17.finance.AccountRequest\x1a\x10.finance.Account\x12C\n" +
	"\x11GetAccountsByUser\x12\x0f.finance.UserID\x1a\x1d.finance.ListAccountsResponse\x12@\n" +
	"\rUpdateAccount\x12\x1d.finance.UpdateAccountRequest\x1a\x10.finance.Account\x12:\n" +
	"\rDeleteAccount\x12\x17.finance.AccountRequest\x1a\x10.finance.Account\x12G\n" +
	"\x11AddUserToAccounnt\x12\x17.finance.AccountRequest\x1a\x19.finance.SharingsResponse\x12F\n" +
	"\x0fCreateOperation\x12\x1f.finance.CreateOperationRequest\x1a\x12.finance.Operation\x12=\n" +
	"\fGetOperation\x12\x19.finance.OperationRequest\x1a\x12.finance.Operation\x12h\n" +
	"\x16GetOperationsByAccount\x12-.finance.OperationsByAccountAndFiltersRequest\x1a\x1f.finance.ListOperationsResponse\x12F\n" +
	"\x0fUpdateOperation\x12\x1f.finance.UpdateOperationRequest\x1a\x12.finance.Operation\x12@\n" +
	"\x0fDeleteOperation\x12\x19.finance.OperationRequest\x1a\x12.finance.Operation\x12C\n" +
	"\x0eCreateCategory\x12\x1e.finance.CreateCategoryRequest\x1a\x11.finance.Category\x12C\n" +
	"\vGetCategory\x12\x18.finance.CategoryRequest\x1a\x1a.finance.CategoryWithStats\x12O\n" +
	"\x11GetCategoryByName\x12\x1e.finance.CategoryByNameRequest\x1a\x1a.finance.CategoryWithStats\x12G\n" +
	"\x13GetCategoriesByUser\x12\x0f.finance.UserID\x1a\x1f.finance.ListCategoriesResponse\x12Y\n" +
	"\x1cGetCategoriesWithStatsByUser\x12\x0f.finance.UserID\x1a(.finance.ListCategoriesWithStatsResponse\x12C\n" +
	"\x0eUpdateCategory\x12\x1e.finance.UpdateCategoryRequest\x1a\x11.finance.Category\x12=\n" +
	"\x0eDeleteCategory\x12\x18.finance.CategoryRequest\x1a\x11.finance.Category\x12V\n" +
	"\x13GetCategoriesReport\x12\x1e.finance.CategoryReportRequest\x1a\x1f.finance.CategoryReportResponseBQZOgithub.com/go-park-mail-ru/2025_2_VKarmane/internal/finance_service/proto;protob\x06proto3"

var (
	file_internal_app_finance_service_proto_finance_proto_rawDescOnce sync.Once
	file_internal_app_finance_service_proto_finance_proto_rawDescData []byte
)

func file_internal_app_finance_service_proto_finance_proto_rawDescGZIP() []byte {
	file_internal_app_finance_service_proto_finance_proto_rawDescOnce.Do(func() {
		file_internal_app_finance_service_proto_finance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_app_finance_service_proto_finance_proto_rawDesc), len(file_internal_app_finance_service_proto_finance_proto_rawDesc)))
	})
	return file_internal_app_finance_service_proto_finance_proto_rawDescData
}

var file_internal_app_finance_service_proto_finance_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_internal_app_finance_service_proto_finance_proto_goTypes = []any{
	(*Account)(nil),                              // 0: finance.Account
	(*CreateAccountRequest)(nil),                 // 1: finance.CreateAccountRequest
	(*UpdateAccountRequest)(nil),                 // 2: finance.UpdateAccountRequest
	(*AccountRequest)(nil),                       // 3: finance.AccountRequest
	(*UserID)(nil),                               // 4: finance.UserID
	(*ListAccountsResponse)(nil),                 // 5: finance.ListAccountsResponse
	(*Operation)(nil),                            // 6: finance.Operation
	(*OperationInList)(nil),                      // 7: finance.OperationInList
	(*CreateOperationRequest)(nil),               // 8: finance.CreateOperationRequest
	(*UpdateOperationRequest)(nil),               // 9: finance.UpdateOperationRequest
	(*OperationRequest)(nil),                     // 10: finance.OperationRequest
	(*ListOperationsResponse)(nil),               // 11: finance.ListOperationsResponse
	(*Category)(nil),                             // 12: finance.Category
	(*CreateCategoryRequest)(nil),                // 13: finance.CreateCategoryRequest
	(*UpdateCategoryRequest)(nil),                // 14: finance.UpdateCategoryRequest
	(*CategoryRequest)(nil),                      // 15: finance.CategoryRequest
	(*CategoryByNameRequest)(nil),                // 16: finance.CategoryByNameRequest
	(*ListCategoriesResponse)(nil),               // 17: finance.ListCategoriesResponse
	(*CategoryWithStats)(nil),                    // 18: finance.CategoryWithStats
	(*ListCategoriesWithStatsResponse)(nil),      // 19: finance.ListCategoriesWithStatsResponse
	(*CategoryReportRequest)(nil),                // 20: finance.CategoryReportRequest
	(*CategoryInReport)(nil),                     // 21: finance.CategoryInReport
	(*CategoryReportResponse)(nil),               // 22: finance.CategoryReportResponse
	(*OperationsByAccountAndFiltersRequest)(nil), // 23: finance.OperationsByAccountAndFiltersRequest
	(*SharingsResponse)(nil),                     // 24: finance.SharingsResponse
	(*timestamppb.Timestamp)(nil),                // 25: google.protobuf.Timestamp
}
var file_internal_app_finance_service_proto_finance_proto_depIdxs = []int32{
	25, // 0: finance.Account.created_at:type_name -> google.protobuf.Timestamp
	25, // 1: finance.Account.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: finance.ListAccountsResponse.accounts:type_name -> finance.Account
	25, // 3: finance.Operation.created_at:type_name -> google.protobuf.Timestamp
	25, // 4: finance.Operation.date:type_name -> google.protobuf.Timestamp
	25, // 5: finance.OperationInList.created_at:type_name -> google.protobuf.Timestamp
	25, // 6: finance.OperationInList.date:type_name -> google.protobuf.Timestamp
	25, // 7: finance.CreateOperationRequest.date:type_name -> google.protobuf.Timestamp
	25, // 8: finance.UpdateOperationRequest.created_at:type_name -> google.protobuf.Timestamp
	7,  // 9: finance.ListOperationsResponse.operations:type_name -> finance.OperationInList
	25, // 10: finance.Category.created_at:type_name -> google.protobuf.Timestamp
	25, // 11: finance.Category.updated_at:type_name -> google.protobuf.Timestamp
	12, // 12: finance.ListCategoriesResponse.categories:type_name -> finance.Category
	12, // 13: finance.CategoryWithStats.category:type_name -> finance.Category
	18, // 14: finance.ListCategoriesWithStatsResponse.categories:type_name -> finance.CategoryWithStats
	25, // 15: finance.CategoryReportRequest.start:type_name -> google.protobuf.Timestamp
	25, // 16: finance.CategoryReportRequest.end:type_name -> google.protobuf.Timestamp
	21, // 17: finance.CategoryReportResponse.categories:type_name -> finance.CategoryInReport
	25, // 18: finance.CategoryReportResponse.start:type_name -> google.protobuf.Timestamp
	25, // 19: finance.CategoryReportResponse.end:type_name -> google.protobuf.Timestamp
	25, // 20: finance.OperationsByAccountAndFiltersRequest.date:type_name -> google.protobuf.Timestamp
	25, // 21: finance.SharingsResponse.created_at:type_name -> google.protobuf.Timestamp
	1,  // 22: finance.FinanceService.CreateAccount:input_type -> finance.CreateAccountRequest
	3,  // 23: finance.FinanceService.GetAccount:input_type -> finance.AccountRequest
	4,  // 24: finance.FinanceService.GetAccountsByUser:input_type -> finance.UserID
	2,  // 25: finance.FinanceService.UpdateAccount:input_type -> finance.UpdateAccountRequest
	3,  // 26: finance.FinanceService.DeleteAccount:input_type -> finance.AccountRequest
	3,  // 27: finance.FinanceService.AddUserToAccounnt:input_type -> finance.AccountRequest
	8,  // 28: finance.FinanceService.CreateOperation:input_type -> finance.CreateOperationRequest
	10, // 29: finance.FinanceService.GetOperation:input_type -> finance.OperationRequest
	23, // 30: finance.FinanceService.GetOperationsByAccount:input_type -> finance.OperationsByAccountAndFiltersRequest
	9,  // 31: finance.FinanceService.UpdateOperation:input_type -> finance.UpdateOperationRequest
	10, // 32: finance.FinanceService.DeleteOperation:input_type -> finance.OperationRequest
	13, // 33: finance.FinanceService.CreateCategory:input_type -> finance.CreateCategoryRequest
	15, // 34: finance.FinanceService.GetCategory:input_type -> finance.CategoryRequest
	16, // 35: finance.FinanceService.GetCategoryByName:input_type -> finance.CategoryByNameRequest
	4,  // 36: finance.FinanceService.GetCategoriesByUser:input_type -> finance.UserID
	4,  // 37: finance.FinanceService.GetCategoriesWithStatsByUser:input_type -> finance.UserID
	14, // 38: finance.FinanceService.UpdateCategory:input_type -> finance.UpdateCategoryRequest
	15, // 39: finance.FinanceService.DeleteCategory:input_type -> finance.CategoryRequest
	20, // 40: finance.FinanceService.GetCategoriesReport:input_type -> finance.CategoryReportRequest
	0,  // 41: finance.FinanceService.CreateAccount:output_type -> finance.Account
	0,  // 42: finance.FinanceService.GetAccount:output_type -> finance.Account
	5,  // 43: finance.FinanceService.GetAccountsByUser:output_type -> finance.ListAccountsResponse
	0,  // 44: finance.FinanceService.UpdateAccount:output_type -> finance.Account
	0,  // 45: finance.FinanceService.DeleteAccount:output_type -> finance.Account
	24, // 46: finance.FinanceService.AddUserToAccounnt:output_type -> finance.SharingsResponse
	6,  // 47: finance.FinanceService.CreateOperation:output_type -> finance.Operation
	6,  // 48: finance.FinanceService.GetOperation:output_type -> finance.Operation
	11, // 49: finance.FinanceService.GetOperationsByAccount:output_type -> finance.ListOperationsResponse
	6,  // 50: finance.FinanceService.UpdateOperation:output_type -> finance.Operation
	6,  // 51: finance.FinanceService.DeleteOperation:output_type -> finance.Operation
	12, // 52: finance.FinanceService.CreateCategory:output_type -> finance.Category
	18, // 53: finance.FinanceService.GetCategory:output_type -> finance.CategoryWithStats
	18, // 54: finance.FinanceService.GetCategoryByName:output_type -> finance.CategoryWithStats
	17, // 55: finance.FinanceService.GetCategoriesByUser:output_type -> finance.ListCategoriesResponse
	19, // 56: finance.FinanceService.GetCategoriesWithStatsByUser:output_type -> finance.ListCategoriesWithStatsResponse
	12, // 57: finance.FinanceService.UpdateCategory:output_type -> finance.Category
	12, // 58: finance.FinanceService.DeleteCategory:output_type -> finance.Category
	22, // 59: finance.FinanceService.GetCategoriesReport:output_type -> finance.CategoryReportResponse
	41, // [41:60] is the sub-list for method output_type
	22, // [22:41] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_internal_app_finance_service_proto_finance_proto_init() }
func file_internal_app_finance_service_proto_finance_proto_init() {
	if File_internal_app_finance_service_proto_finance_proto != nil {
		return
	}
	file_internal_app_finance_service_proto_finance_proto_msgTypes[1].OneofWrappers = []any{}
	file_internal_app_finance_service_proto_finance_proto_msgTypes[2].OneofWrappers = []any{}
	file_internal_app_finance_service_proto_finance_proto_msgTypes[8].OneofWrappers = []any{}
	file_internal_app_finance_service_proto_finance_proto_msgTypes[9].OneofWrappers = []any{}
	file_internal_app_finance_service_proto_finance_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_app_finance_service_proto_finance_proto_rawDesc), len(file_internal_app_finance_service_proto_finance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_app_finance_service_proto_finance_proto_goTypes,
		DependencyIndexes: file_internal_app_finance_service_proto_finance_proto_depIdxs,
		MessageInfos:      file_internal_app_finance_service_proto_finance_proto_msgTypes,
	}.Build()
	File_internal_app_finance_service_proto_finance_proto = out.File
	file_internal_app_finance_service_proto_finance_proto_goTypes = nil
	file_internal_app_finance_service_proto_finance_proto_depIdxs = nil
}
