// Code generated by mockery v2.53.5. DO NOT EDIT.

package balance

import (
	models "github.com/go-park-mail-ru/2025_2_VKarmane/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockBalanceService is an autogenerated mock type for the BalanceService type
type MockBalanceService struct {
	mock.Mock
}

type MockBalanceService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBalanceService) EXPECT() *MockBalanceService_Expecter {
	return &MockBalanceService_Expecter{mock: &_m.Mock}
}

// GetBalanceForUser provides a mock function with given fields: userID
func (_m *MockBalanceService) GetBalanceForUser(userID int) ([]models.Account, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalanceForUser")
	}

	var r0 []models.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]models.Account, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int) []models.Account); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBalanceService_GetBalanceForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalanceForUser'
type MockBalanceService_GetBalanceForUser_Call struct {
	*mock.Call
}

// GetBalanceForUser is a helper method to define mock.On call
//   - userID int
func (_e *MockBalanceService_Expecter) GetBalanceForUser(userID interface{}) *MockBalanceService_GetBalanceForUser_Call {
	return &MockBalanceService_GetBalanceForUser_Call{Call: _e.mock.On("GetBalanceForUser", userID)}
}

func (_c *MockBalanceService_GetBalanceForUser_Call) Run(run func(userID int)) *MockBalanceService_GetBalanceForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockBalanceService_GetBalanceForUser_Call) Return(_a0 []models.Account, _a1 error) *MockBalanceService_GetBalanceForUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBalanceService_GetBalanceForUser_Call) RunAndReturn(run func(int) ([]models.Account, error)) *MockBalanceService_GetBalanceForUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBalanceService creates a new instance of MockBalanceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBalanceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBalanceService {
	mock := &MockBalanceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
