// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/go-park-mail-ru/2025_2_VKarmane/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// OperationRepository is an autogenerated mock type for the OperationRepository type
type OperationRepository struct {
	mock.Mock
}

// GetOperationsByAccount provides a mock function with given fields: ctx, accountID
func (_m *OperationRepository) GetOperationsByAccount(ctx context.Context, accountID int) []models.Operation {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetOperationsByAccount")
	}

	var r0 []models.Operation
	if rf, ok := ret.Get(0).(func(context.Context, int) []models.Operation); ok {
		r0 = rf(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Operation)
		}
	}

	return r0
}

// NewOperationRepository creates a new instance of OperationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOperationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OperationRepository {
	mock := &OperationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
