// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: internal/app/budget_service/proto/budget.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Budget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Sum           float64                `protobuf:"fixed64,3,opt,name=sum,proto3" json:"sum,omitempty"`
	Actual        float64                `protobuf:"fixed64,4,opt,name=actual,proto3" json:"actual,omitempty"`
	CurrencyId    int32                  `protobuf:"varint,5,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ClosedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	PeriodStart   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Budget) Reset() {
	*x = Budget{}
	mi := &file_internal_app_budget_service_proto_budget_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Budget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Budget) ProtoMessage() {}

func (x *Budget) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_budget_service_proto_budget_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Budget.ProtoReflect.Descriptor instead.
func (*Budget) Descriptor() ([]byte, []int) {
	return file_internal_app_budget_service_proto_budget_proto_rawDescGZIP(), []int{0}
}

func (x *Budget) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Budget) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Budget) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *Budget) GetActual() float64 {
	if x != nil {
		return x.Actual
	}
	return 0
}

func (x *Budget) GetCurrencyId() int32 {
	if x != nil {
		return x.CurrencyId
	}
	return 0
}

func (x *Budget) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Budget) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Budget) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Budget) GetClosedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClosedAt
	}
	return nil
}

func (x *Budget) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *Budget) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

type CreateBudgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int32                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Sum           float64                `protobuf:"fixed64,2,opt,name=sum,proto3" json:"sum,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	PeriodStart   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBudgetRequest) Reset() {
	*x = CreateBudgetRequest{}
	mi := &file_internal_app_budget_service_proto_budget_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBudgetRequest) ProtoMessage() {}

func (x *CreateBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_budget_service_proto_budget_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBudgetRequest.ProtoReflect.Descriptor instead.
func (*CreateBudgetRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_budget_service_proto_budget_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBudgetRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *CreateBudgetRequest) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *CreateBudgetRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateBudgetRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CreateBudgetRequest) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *CreateBudgetRequest) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

type UpdateBudgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int32                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	BudgetID      int32                  `protobuf:"varint,2,opt,name=BudgetID,proto3" json:"BudgetID,omitempty"`
	Sum           *float64               `protobuf:"fixed64,3,opt,name=sum,proto3,oneof" json:"sum,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	PeriodStart   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=period_start,json=periodStart,proto3,oneof" json:"period_start,omitempty"`
	PeriodEnd     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=period_end,json=periodEnd,proto3,oneof" json:"period_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBudgetRequest) Reset() {
	*x = UpdateBudgetRequest{}
	mi := &file_internal_app_budget_service_proto_budget_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBudgetRequest) ProtoMessage() {}

func (x *UpdateBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_budget_service_proto_budget_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBudgetRequest.ProtoReflect.Descriptor instead.
func (*UpdateBudgetRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_budget_service_proto_budget_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateBudgetRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *UpdateBudgetRequest) GetBudgetID() int32 {
	if x != nil {
		return x.BudgetID
	}
	return 0
}

func (x *UpdateBudgetRequest) GetSum() float64 {
	if x != nil && x.Sum != nil {
		return *x.Sum
	}
	return 0
}

func (x *UpdateBudgetRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateBudgetRequest) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *UpdateBudgetRequest) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

type BudgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int32                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	BudgetID      int32                  `protobuf:"varint,2,opt,name=BudgetID,proto3" json:"BudgetID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BudgetRequest) Reset() {
	*x = BudgetRequest{}
	mi := &file_internal_app_budget_service_proto_budget_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetRequest) ProtoMessage() {}

func (x *BudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_budget_service_proto_budget_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetRequest.ProtoReflect.Descriptor instead.
func (*BudgetRequest) Descriptor() ([]byte, []int) {
	return file_internal_app_budget_service_proto_budget_proto_rawDescGZIP(), []int{3}
}

func (x *BudgetRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *BudgetRequest) GetBudgetID() int32 {
	if x != nil {
		return x.BudgetID
	}
	return 0
}

type UserID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int32                  `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserID) Reset() {
	*x = UserID{}
	mi := &file_internal_app_budget_service_proto_budget_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserID) ProtoMessage() {}

func (x *UserID) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_budget_service_proto_budget_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserID.ProtoReflect.Descriptor instead.
func (*UserID) Descriptor() ([]byte, []int) {
	return file_internal_app_budget_service_proto_budget_proto_rawDescGZIP(), []int{4}
}

func (x *UserID) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type ListBudgetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Budgets       []*Budget              `protobuf:"bytes,2,rep,name=budgets,proto3" json:"budgets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBudgetsResponse) Reset() {
	*x = ListBudgetsResponse{}
	mi := &file_internal_app_budget_service_proto_budget_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBudgetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBudgetsResponse) ProtoMessage() {}

func (x *ListBudgetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_app_budget_service_proto_budget_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBudgetsResponse.ProtoReflect.Descriptor instead.
func (*ListBudgetsResponse) Descriptor() ([]byte, []int) {
	return file_internal_app_budget_service_proto_budget_proto_rawDescGZIP(), []int{5}
}

func (x *ListBudgetsResponse) GetBudgets() []*Budget {
	if x != nil {
		return x.Budgets
	}
	return nil
}

var File_internal_app_budget_service_proto_budget_proto protoreflect.FileDescriptor

const file_internal_app_budget_service_proto_budget_proto_rawDesc = "" +
	"\n" +
	".internal/app/budget_service/proto/budget.proto\x12\x06budget\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc7\x03\n" +
	"\x06Budget\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x10\n" +
	"\x03sum\x18\x03 \x01(\x01R\x03sum\x12\x16\n" +
	"\x06actual\x18\x04 \x01(\x01R\x06actual\x12\x1f\n" +
	"\vcurrency_id\x18\x05 \x01(\x05R\n" +
	"currencyId\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x127\n" +
	"\tclosed_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\bclosedAt\x12=\n" +
	"\fperiod_start\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd\"\x96\x02\n" +
	"\x13CreateBudgetRequest\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x05R\x06UserID\x12\x10\n" +
	"\x03sum\x18\x02 \x01(\x01R\x03sum\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fperiod_start\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd\"\xc3\x02\n" +
	"\x13UpdateBudgetRequest\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x05R\x06UserID\x12\x1a\n" +
	"\bBudgetID\x18\x02 \x01(\x05R\bBudgetID\x12\x15\n" +
	"\x03sum\x18\x03 \x01(\x01H\x00R\x03sum\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12B\n" +
	"\fperiod_start\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\vperiodStart\x88\x01\x01\x12>\n" +
	"\n" +
	"period_end\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x03R\tperiodEnd\x88\x01\x01B\x06\n" +
	"\x04_sumB\x0e\n" +
	"\f_descriptionB\x0f\n" +
	"\r_period_startB\r\n" +
	"\v_period_end\"C\n" +
	"\rBudgetRequest\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x05R\x06UserID\x12\x1a\n" +
	"\bBudgetID\x18\x02 \x01(\x05R\bBudgetID\" \n" +
	"\x06UserID\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x05R\x06UserID\"?\n" +
	"\x13ListBudgetsResponse\x12(\n" +
	"\abudgets\x18\x02 \x03(\v2\x0e.budget.BudgetR\abudgets2\xb3\x02\n" +
	"\rBudgetService\x12;\n" +
	"\fCreateBudget\x12\x1b.budget.CreateBudgetRequest\x1a\x0e.budget.Budget\x122\n" +
	"\tGetBudget\x12\x15.budget.BudgetRequest\x1a\x0e.budget.Budget\x12=\n" +
	"\x0eGetListBudgets\x12\x0e.budget.UserID\x1a\x1b.budget.ListBudgetsResponse\x12;\n" +
	"\fUpdateBudget\x12\x1b.budget.UpdateBudgetRequest\x1a\x0e.budget.Budget\x125\n" +
	"\fDeleteBudget\x12\x15.budget.BudgetRequest\x1a\x0e.budget.BudgetBTZRgithub.com/go-park-mail-ru/2025_2_VKarmane/internal/app/budget_service/proto;protob\x06proto3"

var (
	file_internal_app_budget_service_proto_budget_proto_rawDescOnce sync.Once
	file_internal_app_budget_service_proto_budget_proto_rawDescData []byte
)

func file_internal_app_budget_service_proto_budget_proto_rawDescGZIP() []byte {
	file_internal_app_budget_service_proto_budget_proto_rawDescOnce.Do(func() {
		file_internal_app_budget_service_proto_budget_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_app_budget_service_proto_budget_proto_rawDesc), len(file_internal_app_budget_service_proto_budget_proto_rawDesc)))
	})
	return file_internal_app_budget_service_proto_budget_proto_rawDescData
}

var file_internal_app_budget_service_proto_budget_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_app_budget_service_proto_budget_proto_goTypes = []any{
	(*Budget)(nil),                // 0: budget.Budget
	(*CreateBudgetRequest)(nil),   // 1: budget.CreateBudgetRequest
	(*UpdateBudgetRequest)(nil),   // 2: budget.UpdateBudgetRequest
	(*BudgetRequest)(nil),         // 3: budget.BudgetRequest
	(*UserID)(nil),                // 4: budget.UserID
	(*ListBudgetsResponse)(nil),   // 5: budget.ListBudgetsResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_internal_app_budget_service_proto_budget_proto_depIdxs = []int32{
	6,  // 0: budget.Budget.created_at:type_name -> google.protobuf.Timestamp
	6,  // 1: budget.Budget.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 2: budget.Budget.closed_at:type_name -> google.protobuf.Timestamp
	6,  // 3: budget.Budget.period_start:type_name -> google.protobuf.Timestamp
	6,  // 4: budget.Budget.period_end:type_name -> google.protobuf.Timestamp
	6,  // 5: budget.CreateBudgetRequest.created_at:type_name -> google.protobuf.Timestamp
	6,  // 6: budget.CreateBudgetRequest.period_start:type_name -> google.protobuf.Timestamp
	6,  // 7: budget.CreateBudgetRequest.period_end:type_name -> google.protobuf.Timestamp
	6,  // 8: budget.UpdateBudgetRequest.period_start:type_name -> google.protobuf.Timestamp
	6,  // 9: budget.UpdateBudgetRequest.period_end:type_name -> google.protobuf.Timestamp
	0,  // 10: budget.ListBudgetsResponse.budgets:type_name -> budget.Budget
	1,  // 11: budget.BudgetService.CreateBudget:input_type -> budget.CreateBudgetRequest
	3,  // 12: budget.BudgetService.GetBudget:input_type -> budget.BudgetRequest
	4,  // 13: budget.BudgetService.GetListBudgets:input_type -> budget.UserID
	2,  // 14: budget.BudgetService.UpdateBudget:input_type -> budget.UpdateBudgetRequest
	3,  // 15: budget.BudgetService.DeleteBudget:input_type -> budget.BudgetRequest
	0,  // 16: budget.BudgetService.CreateBudget:output_type -> budget.Budget
	0,  // 17: budget.BudgetService.GetBudget:output_type -> budget.Budget
	5,  // 18: budget.BudgetService.GetListBudgets:output_type -> budget.ListBudgetsResponse
	0,  // 19: budget.BudgetService.UpdateBudget:output_type -> budget.Budget
	0,  // 20: budget.BudgetService.DeleteBudget:output_type -> budget.Budget
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_internal_app_budget_service_proto_budget_proto_init() }
func file_internal_app_budget_service_proto_budget_proto_init() {
	if File_internal_app_budget_service_proto_budget_proto != nil {
		return
	}
	file_internal_app_budget_service_proto_budget_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_app_budget_service_proto_budget_proto_rawDesc), len(file_internal_app_budget_service_proto_budget_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_app_budget_service_proto_budget_proto_goTypes,
		DependencyIndexes: file_internal_app_budget_service_proto_budget_proto_depIdxs,
		MessageInfos:      file_internal_app_budget_service_proto_budget_proto_msgTypes,
	}.Build()
	File_internal_app_budget_service_proto_budget_proto = out.File
	file_internal_app_budget_service_proto_budget_proto_goTypes = nil
	file_internal_app_budget_service_proto_budget_proto_depIdxs = nil
}
